### ISSUE TITLE
Why is the connection port always hardcoded to 3307?

### ISSUE THREAD

**Issue by e-vrvr** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1006]
Hi Team,

why is the port always hardcoded to 3307 [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java#L149)? Does this mean the library should always work together with SQL Auth Proxy? (as 3307 is the default port for proxy)
Apologies if this is silly question, but it was not clear to me from the documentation - my original impression was that we can use either CloudSQL Auth Proxy + plain JDBC, OR _this_ cloud-sql-jdbc-socket-factory library to connect directly to the DB instance.
I picked this library because it seemed to fulfill the requirement of using IAM and SSL across entire connection (as opposed to Auth Proxy, where only Proxy <-> Db instance connection is using SSL).
UPD: disclaimer - the connection is made from outside of GCP, so having SSL end-to-end is critical.

Even if you specify the DB url as jdbc://host:port, it will ignore the port and will try to use 3307.

Thanks.

**Comment by kurtisvg** [comment]
This library (the Cloud SQL Java connector) works like a java-native version of the Cloud SQL Auth proxy. It connects to a server side proxy on the Cloud SQL instance, which listens on 3307. See the [About the Cloud SQL Auth proxy page](https://cloud.google.com/sql/docs/mysql/sql-proxy#how-works) for details.
