### ISSUE TITLE
Incorrect result sets are being received, causing ClassCastExceptions and other errors

### ISSUE THREAD

**Issue by charlescapps** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#104]
We use MySQL 2nd generation instance with the Java8 runtime in App Engine standard. Our stack includes Scala, [Slick 3.2.3](http://slick.lightbend.com/news/2018/03/23/slick-3.2.3-released.html), and [HikariCP](https://github.com/brettwooldridge/HikariCP). We are using the version of HikariCP that is specificially bundled with Slick (version `2.5.1` of HikariCP), so these libraries are known to be compatible.

Our current relevant dependencies:
```
<dependency> <!-- Only used locally -->
  <groupId>mysql</groupId>
  <artifactId>mysql-connector-java</artifactId>
  <version>5.1.42</version>
</dependency>
<dependency>
  <groupId>com.google.cloud.sql</groupId>
  <artifactId>mysql-socket-factory</artifactId>
  <version>1.0.11</version>
</dependency>
```

I described these strange errors we are getting in this post to the Cloud SQL google group - https://groups.google.com/forum/#!topic/google-cloud-sql-discuss/5Zvg9m-U1Ec

After comparing when we first started getting these errors to our deploys, it appears that the only potentially related change was when we switched from the "old" JDBC URL to the "new" one for Java8, as described in the [Cloud SQL in App Engine with Java8 documentation](https://cloud.google.com/appengine/docs/standard/java/cloud-sql/using-cloud-sql-mysql).

Our current URL looks something like this: 
```
jdbc:mysql://google/${CLOUD_SQL_DATABASE}?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&serverTimezone=UTC
```

The errors are very intermittent; they only happen for a few minutes every few days. They are quite disturbing; things are happening like the a SQL statement to set the transaction isolation, appears to be attempted to be parsed as a result set for a completely different query! 

*The exact same code works 99.999% of the time, and this issue happens across the board for all sorts of different queries/inserts/etc. and in 2 different microservices, so I really doubt this is an issue with our queries*

This never happened prior to us switching over to the new JDBC URL that specifies this Socket Factory.

Thanks for any help!

Example stacktrace:
```
java.sql.SQLException: Invalid value for getLong() - 'SERIALIZABLE' at 
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) at 
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:988) at 
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:974) at 
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) at 
com.mysql.jdbc.ResultSetImpl.getLong(ResultSetImpl.java:3041) at 
com.mysql.jdbc.ResultSetImpl.getLong(ResultSetImpl.java:2952) at 
com.zaxxer.hikari.pool.HikariProxyResultSet.getLong(HikariProxyResultSet.java) at 
slick.jdbc.JdbcTypesComponent$JdbcTypes$LongJdbcType.getValue$mcJ$sp(JdbcTypesComponent.scala:199) at 
slick.jdbc.BaseResultConverter$mcJ$sp.read$mcJ$sp(JdbcResultConverter.scala:10) at 
slick.jdbc.BaseResultConverter$mcJ$sp.read(JdbcResultConverter.scala:9) at 
slick.jdbc.BaseResultConverter$mcJ$sp.read(JdbcResultConverter.scala:8) at 
slick.relational.ProductResultConverter.read(ResultConverter.scala:53) at 
slick.relational.ProductResultConverter.read(ResultConverter.scala:43) at 
slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:133) at 
slick.relational.ProductResultConverter.read(ResultConverter.scala:53) at 
slick.relational.ProductResultConverter.read(ResultConverter.scala:43) at 
slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36) at 
slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:66) at 
slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176) at 
slick.util.ReadAheadIterator$class.slick$util$ReadAheadIterator$$update(ReadAheadIterator.scala:28) at slick.util.ReadAheadIterator$class.hasNext(ReadAheadIterator.scala:34) at 
slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167) at 
scala.collection.Iterator$class.foreach(Iterator.scala:893) at 
slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167) at 
slick.jdbc.Invoker$class.foreach(Invoker.scala:48) at 
slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15) at 
slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22) at 
slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:216) at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:216) at 
slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275) at
 slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at 
java.lang.Thread.run(Thread.java:745)
```

**Comment by charlescapps** [comment]
I'm going to try rolling back to version `1.0.9` of `mysql-socket-factory` since that's the version the official App Engine docs recommend. I'll report back here if it fixes this issue (the issue is intermittent so I probably won't know for sure for a few days).

**Comment by charlescapps** [comment]
FYI - rolling back to `1.0.9` didn't fix this issue. I'm also investigating if this could be an issue with `slick`.

**Comment by kurtisvg** [comment]
The SocketFactory only produces an authorized connection to your CloudSQL instance. It doesn't modify the data or queries in any way, so it seems unlikely to be causing the issue. 

The one addendum to this is that if you are running on AppEngine Standard, it is using the jnr-unixsocket library to connect to the GAE provided socket in `/cloudsql`. You could try to roll back to a version before the jnr-unixsocket was introduced to see if it is related to that, but be aware that you may see increased latency as a result.

**Comment by charlescapps** [comment]
> The one addendum to this is that if you are running on AppEngine Standard, it is using the jnr-unixsocket library to connect to the GAE provided socket in /cloudsql. You could try to roll back to a version before the jnr-unixsocket was introduced to see if it is related to that, but be aware that you may see increased latency as a result.

As I mentioned in the issue, we are indeed using App Engine Standard. Which version started using the jnr-unixsocket? (I can probably figure this out as well from the release notes).

I verified that rolling back the version of the `slick` library did *not* fix the issue, so I'm still fairly certain that in some way using this socket factory is causing the problem. On Monday, I'm going to try rolling back to the old "java7" style connection string for using Cloud SQL in App Engine standard, which does not use this socket factory, then I will report if the issue doesn't occur for a number of days.

Thanks for any investigation!

**Comment by charlescapps** [comment]
> The SocketFactory only produces an authorized connection to your CloudSQL instance. It doesn't modify the data or queries in any way, so it seems unlikely to be causing the issue.

For what it's worth, it's not like data is being _modified_, it's like the wrong _InputStream_ or socket is being associated with the wrong _Connection_. It's trying to parse a result set for a totally different connection/query as the result set for another connection/query.

The only other cause I could fathom is some change in the MySQL driver being used based on the [Java8 cloud SQL instructions](https://cloud.google.com/appengine/docs/standard/java/cloud-sql/using-cloud-sql-mysql). The driver is now autodetected; none of the examples specify the fully qualified class name for the Driver, and an error is thrown when I do so with this connection string.

**Comment by kurtisvg** [comment]
Just wanted to check - did you make an any progress on this issue? I seem to be unable to replicate.
