### ISSUE TITLE
No Suitable Driver

### ISSUE THREAD

**Issue by wesv80** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#105]
hello, it's my first question, create a database in Cloud Sql (mysql), I'm using Android Studio 3.1 IDE, but I have not been able to make a successful connection, add Google's JDBC dependencies but I have not been able to move forward yet. Could someone orient me or change IDE since apparently all have some particular complication? Thank you.

Code:

`package com.example.waldo.gestionpedidos;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * A sample app that connects to a Cloud SQL instance and lists all available tables in a database.
 */
public class ListTables {
    public static void main(String[] args) throws IOException, SQLException {
        // TODO: fill this in
        // The instance connection name can be obtained from the instance overview page in Cloud Console
        // or by running "gcloud sql instances describe <instance> | grep connectionName".
        String instanceConnectionName = "gest-ped-1454121:southamerica-east1:gesped";

        // TODO: fill this in
        // The database from which to list tables.
        String databaseName = "BddGesPed";

        String username = "root";

        // TODO: fill this in
        // This is the password that was set via the Cloud Console or empty if never set
        // (not recommended).
        String password = "123456";

        if (instanceConnectionName.equals("<insert_connection_name>")) {
            System.err.println("Please update the sample to specify the instance connection name.");
            System.exit(1);
        }

        if (password.equals("<insert_connection_name>")) {
            System.err.println("Please update the sample to specify the mysql password.");
            System.exit(1);
        }

        //[START doc-example]
       
        String jdbcUrl = String.format(
                "jdbc:mysql://google/%s?cloudSqlInstance=%s&"
                        + "socketFactory=com.google.cloud.sql.mysql.SocketFactory",
                databaseName,
                instanceConnectionName);
      
        //Class.forName("com.mysql.jdbc.GoogleDriver");
        Connection connection = DriverManager.getConnection(jdbcUrl,username,password);
        
        //[END doc-example]

        try (Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery("SHOW TABLES");
            while (resultSet.next()) {
                System.out.println(resultSet.getString(1));
            }
        }
    }
}
`

**Comment by kurtisvg** [comment]
Can you post the error you are receiving?  Did you add the driver to your pom or build.gradle as well?

**Comment by wesv80** [comment]
Detail message : "java.sql.SQLExeption: no suitable driver"
this code : build.gradle
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "com.example.waldo.gestionpedidos"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.google.android.gms:play-services-maps:12.0.1'
    implementation 'com.google.android.gms:play-services:12.0.1'
    testImplementation 'junit:junit:4.12'
    implementation files('src/main/java/com/example/waldo/gestionpedidos/ksoap2-android-assembly-3.0.0-jar-with-dependencies.jar')
    compileOnly 'com.google.cloud.sql:mysql-socket-factory-connector-j-8:1.0.11'
}
`

**Comment by kurtisvg** [comment]
You need to add the JDBC driver to your dependencies. You can find it on maven [here](https://mvnrepository.com/artifact/mysql/mysql-connector-java/8.0.12).
