### ISSUE TITLE
Upgrade Guava to the latest version

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#109]
[Spring Cloud GCP](https://github.com/spring-cloud/spring-cloud-gcp) uses `com.google.cloud.sql:postgres-socket-factory` for our Postgres with Spring on GCP starter. We have recently turned on Snyk vulnerability detection, and it found a [deserialization issue](https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236) with Guava 20.0. 
The recommended remediation step is to upgrade to 24.1.1 or higher.

Would it be possible to upgrade Guava version in [jdbc-socket-factory-core](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/8a9435277f3856796b0cc86088729a1a068cff50/core/pom.xml#L39)?

Spring Cloud GCP tracking issue: spring-cloud/spring-cloud-gcp#1207

**Comment by elefeint** [comment]
Thank you!

**Comment by elefeint** [comment]
@kurtisvg Would it be possible to get a release cut with this change?

**Comment by kurtisvg** [comment]
@elefeint Yes, I'm planning to trigger the release this afternoon or early tomorrow (waiting on some verification that other changes are working as planned)

**Comment by kurtisvg** [comment]
I've triggered a new release, should be present on Maven Central shortly.
