### ISSUE TITLE
Cloud SQL Socket Factory JDBC connector version upgrade issues. 

### ISSUE THREAD

**Issue by pedrosdf** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1090]
Issue Summary:
The customer currently has MySQL Socket Factory version 1.0.9 [1] (version from 2018) and they are unable to upgrade it to any version newer than the one they currently have. The most recent version is 1.8.0 [2] (released in December 2022). 
The main issue here is that the customer is getting connection errors like SSL exceptions (''No suitable driver'') that are related to socket version discrepancies in which the solution is to upgrade the connector version to ensure compatibility [3], but every time the customer tries to upgrade it, they receive the 'no suitable driver' SQLException during the Kubernetes rollout status check.

They already followed the documentation [4]

Note: The customer already opened a ticket on Google Cloud Support, but they recommended to open the issue here in github, since the issue seems to come from MySQL Socket Factory library and not from the Cloud SQL product.

Cx info:
- MySQL Socket Factory [1] version 1.0.9
- JDK: The services use multiple versions: 8, 11, 13, 14 & 15.
- Gradle dependencies:
implementation 'com.google.cloud.sql:mysql-socket-factory:1.0.9'
implementation 'com.google.cloud.sql:mysql-socket-factory:1.7.2'

Business Impact: 
The customer is unable to have a proper connection from their app container to their Cloud SQL instance (App Container > Cloud SQL Auth Proxy > Cloud SQL MySQL) and are constantly getting (''No suitable driver'') exceptions. 

[1] https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/tag/v1.0.9 
[2] https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/tag/v1.8.0 
[3]
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#troubleshooting 
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/105 
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/39 
[4] 
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#building-the-drivers 
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc-mysql.md

**Comment by enocom** [comment]
Closing as stale. Feel free to re-open with any new information.
