### ISSUE TITLE
Update App Engine detection for new Java Standard GAE runtime 

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#110]
We are working on a newer Java Standard GAE runtime, without the compat layer...
In this execution env, "com.google.appengine.runtime.environment" is not set at all. only GAE_ENV
So
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/connector-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java#L57

does not work.
We are currently forced to use the undocumented CLOUD_SQL_FORCE_UNIX_SOCKET env var to make it work.

**Comment by ludoch** [comment]
In this new GAE Standads Java env com.google.appengine.runtime.environment is neither set to true or false
In the existing GAE Java8 Standard env, it is either set to true or to false.

**Comment by kurtisvg** [comment]
The `CLOUD_SQL_FORCE_UNIX_SOCKET` env var is documented in the project's [README](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/README.md#connection-via-unix-sockets).

Moving forward, what is the preferred method for detecting if the SF is executing in this new environment?

**Comment by ludoch** [comment]
String gaeEnv = System.getenv("GAE_ENV");

is still "standard"

    String runEnv = System.getProperty("com.google.appengine.runtime.environment");

should be null in this environment (so neither prod nor dev).

**Comment by kurtisvg** [comment]
Offline info + some summary on this:

We can detect the new environment when `GAE_ENV="standard"` and `GAE_RUNTIME="java11"`. 

We should be able to support both versions with the following logic: 
`GAE_ENV == "standard"` and either `com.google.appengine.runtime.environment == "Production"` or `GAE_RUNTIME == "java11"`
