### ISSUE TITLE
Update Example to Follow Best Practice

### ISSUE THREAD

**Issue by Kool-Koder** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#111]
Hi, I would like to suggest the following sample code to use prepared statement instead. I may try to fork it and do a PR soon.

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/examples/compute-engine/src/main/java/com/google/cloud/sql/mysql/example/ListTables.java

**Comment by kurtisvg** [comment]
The sample [here](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/5c552d6126e1fe9808c510794d1171042014d792/cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/IndexServlet.java#L55) uses a PreparedStatement.

The plan is to replace the samples in this repo with a reference to the java-docs-samples.

**Comment by Kool-Koder** [comment]
I see. Great thank you!
