### ISSUE TITLE
obsolete asm dependency

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#112]
On one of my Java11 projects, I had to put this exclusion:

````
   <dependency>
      <groupId>com.google.cloud.sql</groupId>
      <artifactId>postgres-socket-factory</artifactId>
      <version>1.0.11</version>
      <exclusions>
        <exclusion>
          <groupId>org.ow2.asm</groupId>
          <artifactId>asm-util</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

and add this latest (7.0) dep:
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-util</artifactId>
      <version>7.0</version>
    </dependency>
````
to avoid this error:
A  Caused by:  
A  java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-warfile.war-_-any-14146729893299789987.dir/webapp/WEB-INF/classes/com/example/appengine/postgresql/ConnectionPoolContextListener.class
	at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:745)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834) 
A  Caused by:  
A  java.lang.IllegalArgumentException 
A  	at org.objectweb.asm.ClassReader.<init>(Unknown Source) 
A  	at org.objectweb.asm.ClassReader.<init>(Unknown Source) 
A  	at org.objectweb.asm.ClassReader.<init>(Unknown Source) 
A  	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:934) 
A  	at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:739) 
A  	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831)

**Comment by ludoch** [comment]
Maybe we do not need asm at all and it is coming from a wrong dep on Jetty?

**Comment by kurtisvg** [comment]
The ASM dependency is coming from jnr-unixsocket, which in turn is coming from jnr-ffi. There is an issue opened for updting ASM to 7.0 [here](https://github.com/jnr/jnr-ffi/issues/185) which ludoch has commented on. 

According to ASM's [backwards compatibility contract ](https://asm.ow2.io/asm4-guide.pdf#page88) it looks like it should be safe to upgrade to 7.X.
