### ISSUE TITLE
1.0.11 is not backwards compatible to 1.0.10 (postgresql)

### ISSUE THREAD

**Issue by neurolabs** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#113]
in 1.0.10, you could include the `socketFactoryArg` parameter in your jdbc url in order to pass the cloudSqlInstance name. In 1.0.11, doing this leads to the value not being found by the SocketFactory constructor, failing the call to `checkArgument` in line 53 of `com.google.cloud.sql.postgres.SocketFactory`.

IMHO, API breakage should not happen on micro bumps. There also is no explicit reference to this in the release notes AFAICS.

**Comment by neurolabs** [comment]
Forward fix is to rename the `socketFactoryArg` parameter in the jdbc url to `cloudSqlInstance`.

**Comment by kurtisvg** [comment]
My understanding with this API change is that older versions of the connector will call [this](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/8a9435277f3856796b0cc86088729a1a068cff50/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java#L64) deprecated version, while newer versions of the connector should call the newer one [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/8a9435277f3856796b0cc86088729a1a068cff50/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java#L51).  I remember verifying this at the time, but it has been a while so perhaps I'm mis-remembering.

**Comment by neurolabs** [comment]
I did bump both, the connector (from 42.2.4 to 42.2.5) and this library. But the connector update also is a micro update. I was caught by surprise of this api change. Even if the newer connector calls the new Properties based version, can't it access `socketFactoryArg` from inside of the properties?

The changelog for the postgresql connector also does not seem to mention this change explicitly: https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.5

**Comment by kurtisvg** [comment]
> Even if the newer connector calls the new Properties based version, can't the SocketFactory constructor access socketFactoryArg from inside of the properties?

Yes, that's what it does with this line [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/8a9435277f3856796b0cc86088729a1a068cff50/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java#L66).

**Comment by neurolabs** [comment]
I see. Somehow, in my case, it did not work, I had to change the connection argument name from `socketFactoryArg` to `cloudSqlInstance`.

Well, no harm done, and if there's a backwards compatible route, I think we can close this.

**Comment by kurtisvg** [comment]
I'm going to leave this open until I can re-verify the backwards compatibility is working correctly. I'll update when I've clarified in what situations it does/doesn't work in.

**Comment by kurtisvg** [comment]
I think what's happening is that when the older connector is used, it's converting `SocketFactoryArg` property into `instanceName` arg and calling the old api, but when the new connector is used it's calling the new api which doesn't specifically check for SocketFactoryArg.

**Comment by neurolabs** [comment]
yes, of course, you're right.

**Comment by kurtisvg** [comment]
I've also updated the release note for v1.0.11 so that this bug it documented there.
