### ISSUE TITLE
Support DNS names for `cloudSqlInstance`

### ISSUE THREAD

**Issue by RB14** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1153]
## Feature Description
Hello, 

We have a use case in our application where our database instance is being replaced every day and we need our application to reconnect to it automatically when that happens. The approach we took for the solution is that we created a DNS record which points at the **private ip** of our Cloud SQL instance, and configured the connection pool of our app to use that DNS name. When the instance is being replaced, the process that replaced it would also update the DNS record to point to the private IP of the new instance.

The problem with this approach is that we can't use Cloud SQL Proxy (or the various connectors) for the connection, since Cloud SQL Proxy requires to specify the instance **name** upon **initialization** of the connector, or, alternatively, requires to **restart** the `cloud_sql_proxy` process, which is external to the the application, may require a short downtime, and makes it  more difficult.

I would like to propose a feature for the Cloud SQL Connector library, which would allow to specify the `cloudSqlInstance` via a DNS name. That DNS would be of type [`TXT`](https://en.wikipedia.org/wiki/TXT_record), and its content will be the same content we currently have to pass to `cloudSqlInstance`. The way the connector would work is that every time it is asked for a new connection, it will **first** resolve the DNS name, extract the `TXT` record from it, and then pass it to the [`CoreFactory#connect`](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java#L77) method (just like today). I'm not sure if that DNS name should be passed in the conventional `host` parameter, or in another custom parameter, or maybe even to the same `cloudSqlInstance` parameter where you currently expect the instance name, but I'm leaving it for you to decide.

## Alternatives Considered
We have considered several alternatives, but all of them require changes to our architecture (which currently relies on the DNS name)... including restarting the connection pool from the outside, or restarting the `cloud_sql_proxy`... all these solutions are more complicated for us, and we would prefer it we can stick to the DNS solution.

## Additional Context
Using [dynamic] DNS records to point at network resources provides several benefits, but the most significant one is the ability to abstract away the resource from its clients. It allows us to make changes to the resource (e.g. replacing the db instance), while keeping the actual change transparent from the user (just change the DNS name to point at the newly located resource). All that assuming the changes we do are backward compatible on the API level.

**Comment by RB14** [comment]
If you don't like the non-standard use of the `TXT` DNS record I'm suggesting, another approach could be to allow passing a custom `INSTANCE_NAME` **resolver** to the connector. This resolver is a class which has to implement a `resolve()` method (or something similar), which will be called every time a new connection is initialized by the connector. That method will return the name of the Cloud SQL instance (what we currently pass in `cloudSqlInstance`). We can then create our own resolver which can be based on DNS `TXT` record... Or maybe, you can provide some resolvers out of the box, including one for DNS names..

**Comment by RB14** [comment]
Thanks @enocom !

It's good to know that you are already aware of this problem. Our use case is a bit different than disaster-recovery, but I think it has similarities. One of the differences between our use-case and disaster-recovery, is that in our use-case (and generally speaking), we prefer that connections are not restarted abruptly just because the instance has changed.. we prefer that current active connections (active meaning they are currently out of the pool, maybe in the middle of a transaction...), will finish their work, returned to the pool, and only next time the pool lends them, they will be restarted. This use-case is only relevant of the old instance is still up and running... It makes sense because we don't want users of our app to experience failures once a day, so we prefer to first finish what the connections are doing, before restarting them. This is possible with configurations of the connection pool (we use HikariCP). Our use case allows some of the connections to be connected to the old db, while other connections are connected to the new one (however, I do realize this is not a typical use case).

While I think the approach you're talking (by "listening" to an external source), I think there is also room to make it possible to use standard mechanisms to initialize the connection (like using a DNS name, which is very common with other Java JDBC connectors), and let the connection pool decide when to restart the connections. I think an approach where we can specify a Resolver/Provider class, that will dynamically resolve the instance name, is very flexible, and also relatively easy to implement (much easier than a full blown mechanism that also has to listen to some external source).

I hope you'll consider this kind of solution as well when you start working on the other ticket.

Until that happens, we will consider implementing this sort of mechanism in our application, maybe creating our own JDBC connector which delegates to yours (extending yours maybe), so we can use a DNS name.

Appreciate our response!

**Comment by enocom** [comment]
The Connectors are all anchored heavily on a notion of instance connection name -- which the connectors use to resolve to an IP address in the SQL Admin API. 

One of the problems with trying to put DNS between that and the Admin API response, is that we're now opening up a potential security problem (e.g., are you actually connecting to the database specified by the instance connection name). Seems like what you really want here is some kind of way to balance load across databases, with databases coming and going. You might think about using a server side connection pooler like pgbouncer which could encapsulate the backing databases from you apps.

**Comment by RB14** [comment]
> One of the problems with trying to put DNS between that and the Admin API response, is that we're now opening up a potential security problem (e.g., are you actually connecting to the database specified by the instance connection name)

The DNS would include the exact same value you currently pass to  the `cloudSqlInstance` parameter, it shouldn't work any other way... it will just be a dynamic value instead of static. Basically what you will do is just resolve the DNS, extract the value from it, and put it in the `cloudSqlInstance` in the `Properties` object.

> Seems like what you really want here is some kind of way to balance load across databases, with databases coming and going.

Not exactly, I didn't go into too much details about our use case because I honestly think the solution should not be tightly coupled to our use-case, and I honestly believe the problem I'm describing is pretty generic. Pgbouncer won't work since it would still require us to change its configuration every single day (our DB is being replaced every day). And pbouncer itself would still need to connect through Cloud SQL Proxy, right? (that's actually a requirement for us due to SSL encryption), we would have the same challenges. In any case we don't need load balancing in our use case, we just want to avoid restarting connection in the middle of an operation, but once the operation is done, connection are restarted against the new db instance (and never go back to the old one).

I think the idea of using DNS was pretty specific, I think we should pursue a solution like the one I described in comment#2. This solution would allow users of the library to provide their own implementation for a **dynamic resolver**, one such implementation could be the DNS resolver... Note that no matter the solution, the result of the resolver will always be used to populate the `cloudSqlInstance` parameter, so it is expected that the result will always be a valid Cloud SQL instance name.

**Comment by enocom** [comment]
So to summarize a conversation elsewhere, we're talking about providing a way to resolve the instance connection name at runtime.

Since the Java connector runs a background thread to refresh instance certificates, I think that means we'd be doing this as part of the refresh cycle. Given the potential lag between a refresh cycle and a new instance being available, we might have to make this refresh cycle lazy when a resolver was provided. That way you'd always get the latest instance connection name for a connection.

**Comment by enocom** [comment]
Given some further thought on this, I think the Java connector isn't the right place for this feature. This would be a big departure from how the other Cloud SQL Connectors work and would require the refresh cycle to happen largely in the foreground. We might revisit request in the future if/when Cloud SQL treats DNS resolution as a first class concern in the product.
