### ISSUE TITLE
Add service account impersonation

### ISSUE THREAD

**Issue by fzakaria** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1168]
### Feature Description

In order to support P4SA setup for Google Cloud, it would be great to add the ability to easily do service account impersonation in a common way across all connectors.

Briefly looking at the MySQL connector, I think this can be accomplished by writing a new custom GoogleCredentialFactory ourselves. Given the popularity of likely wanting to provide service account impersonation, it would be great to include it default in the standard factory.

### Alternatives Considered

We are considering writing our own factory for now.

**Comment by enocom** [comment]
We're working on a v2 of the Java Connector and this is one of the features we want to include.

**Comment by enocom** [comment]
On some further discussion, we're going to work on this and get some refactoring done as part of it and land this as part of v1 if it doesn't necessitate any breaking changes.
