### ISSUE TITLE
Update google-api-services-sqladmin version to 1.28

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#121]
Right now `google-api-services-sqladmin` version is 1.23, which brings in an old version of com.fasterxml.jackson.core:jackson-core (v2.1.3) by way of google-http-client-jackson2 (v1.23). There are a couple of DoS vulnerabilities affecting old jackson versions ([link](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31520), [link](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31519)).

Bumping `google-api-services-sqladmin` version to the latest, 1.28, should take care of this.
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/963c25991bf91dd0e25fb93f405794cff87e4e8d/core/pom.xml#L23

**Comment by kurtisvg** [comment]
The latest version I see is on maven central is [1.25.0 ](https://mvnrepository.com/artifact/com.google.apis/google-api-services-sqladmin)- should there have been a 1.28.0 release?

**Comment by elefeint** [comment]
It is searchable on[ maven.org](https://search.maven.org/artifact/com.google.apis/google-api-services-sqladmin/v1beta4-rev20181031-1.28.0/jar); not sure why it's not visible on mvnrepository.com.

**Comment by elefeint** [comment]
Would it be possible to have a 1.0.13 release with this?

**Comment by kurtisvg** [comment]
> Would it be possible to have a 1.0.13 release with this?

Sure, but it will likely be a week or two before I get a chance to release next.

**Comment by elefeint** [comment]
That's no problem, thank you!

**Comment by kurtisvg** [comment]
@elefeint Thanks for the wait - I've released v1.0.13 and it being to show up on mirrors in the next couple of hours.
