### ISSUE TITLE
Do I need to manually import `io.asyncer:r2dbc-mysql` on my Maven project?

### ISSUE THREAD

**Issue by diegomarquezp** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1328]
### Question

A [recent update to `1.12.0`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1950) in spring-cloud-gcp brought a regression in our Cloud SQL MySQL R2DBC sample/integration test ([details](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1951#issuecomment-1591912710))

According to https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/24e35149b74e661276607e6b8341ca518ed91427/docs/r2dbc-mysql.md?plain=1#L23

We have to manually add this dependency, but before `1.12.0` we didn't have to. I wonder if this is a new requirement for us (or the sample users).

**Comment by diegomarquezp** [comment]
Needs an update given https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/commit/974c19935ff0ef7493c9cca23721dbc64d7a5085

**Comment by enocom** [comment]
@diegomarquezp Did you find what you needed here?

**Comment by enocom** [comment]
Got it. Let me know if we help in that case.
