### ISSUE TITLE
Update mysql-connector-java version to 8.0.16

### ISSUE THREAD

**Issue by BalajiPonniah** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#139]
Hi guys, latest mysql connector solves SSL issue https://bugs.mysql.com/bug.php?id=93590.
Is it possible update to latest version for resolving this issue ?

**Comment by kurtisvg** [comment]
Hey @BalajiPonniah - The next release will be about the first week of June, and will include bumping the connector to it's latest version.
