### ISSUE TITLE
TLSv1.2 for IAM auth_type

### ISSUE THREAD

**Issue by sandl99** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1398]
### Question

Hi masters, I've encountered a problem which shows that my Java doesn't support TLSv1.3. In your implementation, it seems like AuthType.IAM would be used with TLSv1.3, so Is possible If I change to TLSv1.2 to use IAM auth type ?

```
Caused by: java.security.NoSuchAlgorithmException: TLSv1.3 SSLContext not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at com.google.cloud.sql.core.SqlAdminApiFetcher.createSslData(SqlAdminApiFetcher.java:332)
```

### Code

```Java
try {
        sslContext = SSLContext.getInstance("TLSv1.3");
      } catch (NoSuchAlgorithmException ex) {
        if (authType == AuthType.IAM) {
          throw new RuntimeException(
              String.format(
                      "[%s] Unable to create a SSLContext for the Cloud SQL instance.",
                      instanceName.getConnectionName())
                  + " TLSv1.3 is not supported for your Java version and is required to connect"
                  + " using IAM authentication",
              ex);
        } else {
          logger.warning("TLSv1.3 is not supported for your Java version, fallback to TLSv1.2");
          sslContext = SSLContext.getInstance("TLSv1.2");
        }
      }
```

**Comment by enocom** [comment]
Unfortunately no, and there's a good reason.

Auto IAM AuthN works by embedding an OAuth2 token into the ephemeral certificate as a SAN. As part of the initial handshake, the Java Connector presents that cert to the server side Proxy. If we use TLS 1.2, the certificates will be exchanged over an unencrypted channel which would amount to transmitting your OAuth2 token in the clear. That's bad. Instead with TLS 1.3, the certificates are exchanged over an encrypted connection, and so it's OK to send the client cert with the OAuth2 token.

As a result, we ensure clients use TLS 1.3 to avoid leaking their OAuth2 token.
