### ISSUE TITLE
Use updated maven configs and github actions

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1447]
### Feature Description

The [java-shared-config](https://github.com/googleapis/java-shared-config) repository should be the parent of this repository. However, since this repo is older, the pom.xml files contain a lot of redundant and slightly different configuration.

- [ ] Set [java-shared-config/pom.xml](https://github.com/googleapis/java-shared-config) as the parent
- [ ] Eliminate redundant, outdated, and misaligned configuration from this project's pom.xml files.
- [ ] Update build scripts to use the updated maven targets and profiles
- [ ] Update github actions

**Comment by ttosta-google** [comment]
The mentioned changes are included in this PR https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/1530. Can we close this issue?

**Comment by hessjcg** [comment]
Fixed by #1530
