### ISSUE TITLE
Dependency Issues when using Pyspark

### ISSUE THREAD

**Issue by lf2netr0** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#155]
I try to use with pyspark

```
conf = pyspark.SparkConf().setAll([('spark.executor.memory', '32g'), ('spark.executor.cores', '12'), ('spark.driver.memory','32g'), ('spark.jars.packages', 'mysql:mysql-connector-java:8.0.17,com.google.cloud.sql:mysql-socket-factory-connector-j-8:1.0.14')])
spark = SparkSession.builder\
    .appName("myApp")\
    .config(conf=conf)\
    .getOrCreate()
```
I got this error:

> java.io.FileNotFoundException: File file:/root/.ivy2/jars/com.github.jnr_jffi-1.2.19.jar does not exist

There is no error in 1.0.13.
But I got error below in 1.0.13:

> java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;
> at com.google.api.client.http.UriTemplate.expand(UriTemplate.java:305)
> 	at com.google.api.client.http.UriTemplate.expand(UriTemplate.java:262)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequestUrl(AbstractGoogleClientRequest.java:362)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:397)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
> 	at com.google.cloud.sql.core.CoreSocketFactory.obtainInstanceMetadata(CoreSocketFactory.java:478)
> 	at com.google.cloud.sql.core.CoreSocketFactory.fetchInstanceSslInfo(CoreSocketFactory.java:396)
> 	at com.google.cloud.sql.core.CoreSocketFactory.getInstanceSslInfo(CoreSocketFactory.java:376)
> 	at com.google.cloud.sql.core.CoreSocketFactory.createAndConfigureSocket(CoreSocketFactory.java:258)
> 	at com.google.cloud.sql.core.CoreSocketFactory.createSslSocket(CoreSocketFactory.java:227)
> 	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:199)
> 	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:51)
> 	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:38)
> 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
> 	at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
> 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
> 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
> 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
> 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
> 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
> 	at org.apache.spark.sql.execution.datasources.jdbc.DriverWrapper.connect(DriverWrapper.scala:45)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:63)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:54)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:56)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:210)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
> 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
> 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by kurtisvg** [comment]
I'm not familiar with pyspark, but this looks like it's failing to pull in a dependency?

How are the jars supplied to pyspark? Does it use maven or gradle? Have you tried using one of the uber-jars from the releases page?

**Comment by lf2netr0** [comment]
I checked the jar path ,then I found `com.github.jnr_jffi-1.2.19-native.jar` pulled from maven.
So it can not find the jar file. After renamed, it work.

But got new error when connect to cloud SQL(mysql 2nd 5.7) like :
```
dataframe_mysql = spark.read.format("jdbc").option("driver", "com.mysql.cj.jdbc.Driver")\
    .option("url", "jdbc:mysql://google/{db}/?cloudSqlInstance={cloudSqlInstance}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&user=root&password=password").load()
```
And error below :

> Py4JJavaError: An error occurred while calling o74.load.
> : java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
> 	at com.google.cloud.sql.core.CloudSqlInstance.getInstanceData(CloudSqlInstance.java:126)
> 	at com.google.cloud.sql.core.CloudSqlInstance.createSslSocket(CloudSqlInstance.java:136)
> 	at com.google.cloud.sql.core.CoreSocketFactory.createSslSocket(CoreSocketFactory.java:226)
> 	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:187)
> 	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:48)
> 	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:38)
> 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
> 	at com.mysql.cj.NativeSession.connect(NativeSession.java:150)
> 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:947)
> 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:817)
> 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
> 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
> 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
> 	at org.apache.spark.sql.execution.datasources.jdbc.DriverWrapper.connect(DriverWrapper.scala:45)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:63)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:54)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:56)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:210)
> 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
> 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
> 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by kurtisvg** [comment]
It sounds like it might be still missing a dependency. Can you use one of the jar-with-dependencies from the [releases page](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases) and see if that solves your issue?

**Comment by lf2netr0** [comment]
I tried the released jar-with-dependencies , still got the same error.

**Comment by lf2netr0** [comment]
Finally, I connect to Cloud SQL successfully by `mysql-socket-factory-connector-j-8-1.0.12-jar-with-dependencies.jar` and `mysql:mysql-connector-java:8.0.13`

There are errors about method not found in `com.google.common.base` for these version :

`mysql-socket-factory-connector-j-8-1.0.13-jar-with-dependencies.jar`
`mysql-socket-factory-connector-j-6-1.0.14-jar-with-dependencies.jar`
`mysql-socket-factory-connector-j-8-1.0.14-jar-with-dependencies.jar`

**Comment by kurtisvg** [comment]
It sounds like you must have another dependency in the classpath that is providing an older version of guava that doesn't have the `Throwables.throwIfUnchecked` method. 

I'm going to close this since you were able to resolve the issue.
