### ISSUE TITLE
Incorrect doc titles?

### ISSUE THREAD

**Issue by seviet** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1635]
### Description

We noticed the docs have been consolidated, because we've had reports of broken x-links in the Google Cloud SQL docs. 

But wondering why have the titles of the docs been renamed to "Connecting to SQL Server using JDBC" and "Connecting to SQL Server using R2DBC" 

Shouldn't they be titled to "Connecting to Cloud SQL using JDBC" and "Connecting to Cloud SQL using R2DBC"  ?

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc.md

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/r2dbc.md

thanks!

**Comment by ttosta-google** [comment]
Thank you @seviet for pointing that out. I've fixed it under PR #1638
