### ISSUE TITLE
Does not support passwords with '*' character

### ISSUE THREAD

**Issue by AndrewBell** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#167]
I noticed this integrating a new project. I had generated a password (via Terraform) containing a '*' character. I was able to connect to my database in the Cloud Console without issue, but when trying to connect with the socket factory I'd get `Access denied for user 'my-user'@'cloudsqlproxy~34.67.249.122' (using password: YES)`

It may not have been the '*' character, I had a '%' in there as well, but saw a suggestion elsewhere to avoid characters that may be interpreted as a wildcard and it's possible this library is doing something similar. Let me know if there's anything else I can do to help.

In case anyone comes across this who's using terraform, I used the `override_special` property to define a limited set of special characters, excluding any common offenders, and was then able to connect.

**Comment by kurtisvg** [comment]
I don't think this is related to this library - the Socket Factory doesn't handle the username and password (that would be up to your connection pooler / driver). 

Feel free to reopen if you can pinpoint the JDBC Socket Factory as the problem maker here.
