### ISSUE TITLE
Error when trying to connect to CloudSQL from datafusion

### ISSUE THREAD

**Issue by BapediBoupi** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#170]
Hello,

I'm trying to add a CloudSQL DB connection from DataFusion.
Adding the driver from the last release works fine, but when testing connection the following message is displayed:

"Something unusual has occurred to cause the driver to fail. Please report this exception."

Connection string is as follows:
```
jdbc:postgresql://google/{our_db_name}?cloudSqlInstance={our_instance}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
```
Any idea?

Edit from the stacktrace: 
```
2020-02-04 15:13:04,791 - ERROR [pool-141-thread-2:c.g.c.s.c.CloudSqlInstance@392] - Got more than one input failure. Logging failures after the first
java.lang.RuntimeException: [XXXXXXX] The Cloud SQL Instance does not exist or your account is not authorized to access it. Please verify the instance connection name and check the IAM permissions for project &quot;{project_name}&quot; 
```
Adding the CloudSQL rights to the Datafusion service account would be enough?

Thanks!

**Comment by kurtisvg** [comment]
@BapediBoupi Yes, the service account being used to connect needs the `Cloud SQL Client` IAM role (or higher). 

Marking as closed since the stack trace gave you the answer.
