### ISSUE TITLE
Support Cloud Run for Anthos

### ISSUE THREAD

**Issue by nhartner** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#172]
I'm deploying a Spring Boot application on Cloud Run For Anthos (on my own GKE cluster). As such, there is no unix socket created for Cloud SQL connections. But the logic in CoreSocketFactory assumes that this is a Cloud Function and therefore forces unix socket mode which does not work. Specifically, the logic assumes that the ENV vars K_REVISION and K_SERVICE are only set for Cloud Functions. But these env vars are also set by Cloud Run for Anthos. As such, it is impossible to use this library on Cloud Run for Anthos as there is no way to force it not to revert to unix socket mode.

**Comment by kurtisvg** [comment]
Is there a way to detect Cloud Run vs Cloud Run on Anthos?

**Comment by nhartner** [comment]
I don't know. Would it make sense to have an env to force SSL mode? Similar to the CLOUD_SQL_FORCE_UNIX_SOCKET env var.

**Comment by nhartner** [comment]
Looking at the ENV vars set by Cloud Run for Anthos, I'm not seeing anything that would hint that this is Cloud Run for Anthos vs just Cloud Run. These look like the env vars that are being set:
```
export HOSTNAME='neil-connector-457x4-deployment-799cf85d74-ktlkv'
export KUBERNETES_PORT='tcp://10.16.0.1:443'
export KUBERNETES_PORT_443_TCP='tcp://10.16.0.1:443'
export KUBERNETES_PORT_443_TCP_ADDR='10.16.0.1'
export KUBERNETES_PORT_443_TCP_PORT='443'
export KUBERNETES_PORT_443_TCP_PROTO='tcp'
export KUBERNETES_SERVICE_HOST='10.16.0.1'
export KUBERNETES_SERVICE_PORT='443'
export KUBERNETES_SERVICE_PORT_HTTPS='443'
export K_CONFIGURATION='neil-connector'
export K_REVISION='neil-connector-457x4'
export K_SERVICE='neil-connector'
```

**Comment by kurtisvg** [comment]
I definitely would like to give a toggle of some kind to the user, for both SSL and for choosing a custom unix socket (if they prefer).

I think a url component might be better however.
