### ISSUE TITLE
Does Postgres JDBC URL require `ssl=false`?

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#173]
The readme says that the MySQL JDBC URL should have `useSsl=false`, but it doesn't say that for Postgres. Is this intentional?

Related: https://github.com/spring-cloud/spring-cloud-gcp/issues/2206

**Comment by kurtisvg** [comment]
It should be removed for MySQL. The ssl arguments are no-ops - we always use ssl.

**Comment by kurtisvg** [comment]
Closed by #174
