### ISSUE TITLE
Build error due to version dependency on CloudSqlFeature.java

### ISSUE THREAD

**Issue by norman-wong-cn** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1775]
### Question

I cloned the latest 1.15.1 release to Windows 10.
As per Readme, I try build with maven command:

mvn -P jar-with-dependencies clean package -DskipTests

...
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] C:\DATA\155866\cloud-sql-jdbc-socket-factory\core\src\main\java\com\google\cloud\sql\nativeimage\CloudSqlFeature.java:[20,37] error: cannot access Feature
  bad class file: C:\Users\155866\.m2\repository\org\graalvm\sdk\nativeimage\23.1.1\nativeimage-23.1.1.jar(/org/graalvm/nativeimage/hosted/Feature.class)
    class file has wrong version 55.0, should be 53.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Cloud SQL JDBC Socket Factory 1.15.2-SNAPSHOT:
[INFO]
[INFO] Cloud SQL JDBC Socket Factory ...................... SUCCESS [  1.691 s]
[INFO] Cloud SQL Core Socket Factory (Core Library, don't depend on this directly) FAILURE [  3.114 s]
[INFO] Cloud SQL MariaDB Socket Factory ................... SKIPPED
[INFO] Cloud SQL MySQL Socket Factory (for Connector/J 8.x) SKIPPED
[INFO] Cloud SQL Postgres Socket Factory .................. SKIPPED
[INFO] Cloud SQL JDBC Connector for SQL Server ............ SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory (R2DBC Core Library, don't depend on this directly) SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory for MySQL ....... SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory for Postgres .... SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory for SQL Server .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

How do I work around this error?

Thanks,
Norm

**Comment by ttosta-google** [comment]
Please check your java version. Use Java 11 or a later version.

**Comment by norman-wong-cn** [comment]
Same error with Java 11:

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] C:\DATA\155866\cloud-sql-jdbc-socket-factory\core\src\main\java\com\google\cloud\sql\nativeimage\CloudSqlFeature.java:[20,37] error: cannot access Feature
  bad class file: C:\Users\155866\.m2\repository\org\graalvm\sdk\nativeimage\23.1.1\nativeimage-23.1.1.jar(/org/graalvm/nativeimage/hosted/Feature.class)
    class file has wrong version 55.0, should be 53.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Cloud SQL JDBC Socket Factory 1.15.2-SNAPSHOT:
[INFO]
[INFO] Cloud SQL JDBC Socket Factory ...................... SUCCESS [  1.867 s]
[INFO] Cloud SQL Core Socket Factory (Core Library, don't depend on this directly) FAILURE [  3.033 s]
[INFO] Cloud SQL MariaDB Socket Factory ................... SKIPPED
[INFO] Cloud SQL MySQL Socket Factory (for Connector/J 8.x) SKIPPED
[INFO] Cloud SQL Postgres Socket Factory .................. SKIPPED
[INFO] Cloud SQL JDBC Connector for SQL Server ............ SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory (R2DBC Core Library, don't depend on this directly) SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory for MySQL ....... SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory for Postgres .... SKIPPED
[INFO] Cloud SQL R2DBC Connection Factory for SQL Server .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.247 s
[INFO] Finished at: 2024-01-11T11:35:05-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project jdbc-socket-factory-core: Compilation failure
[ERROR] C:\DATA\155866\cloud-sql-jdbc-socket-factory\core\src\main\java\com\google\cloud\sql\nativeimage\CloudSqlFeature.java:[20,37] error: cannot access Feature
[ERROR]   bad class file: C:\Users\155866\.m2\repository\org\graalvm\sdk\nativeimage\23.1.1\nativeimage-23.1.1.jar(/org/graalvm/nativeimage/hosted/Feature.class)
[ERROR]     class file has wrong version 55.0, should be 53.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jdbc-socket-factory-core
PS C:\data\155866\cloud-sql-jdbc-socket-factory> java -version
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\Micro Focus\UFT One\bin\java_shared\classes\jasmine.jar"
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.21+9-adhoc..jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.21+9-adhoc..jdk11u, mixed mode)
PS C:\data\155866\cloud-sql-jdbc-socket-factory>

**Comment by ttosta-google** [comment]
I am able to compile this project on Windows 10 using Java 11.

Please do the following:

1. Confirm the linked Java version of your mvn. `mvn -v`
2. Then confirm which Java version you are using for both your computer and application.
3. If they don't match, feel free to set a JAVA_HOME variable for your desired Java version.
4. After that, do a maven build of your application. `mvn clean -P jar-with-dependencies clean package -DskipTests`

**Comment by norman-wong-cn** [comment]
Thanks for your help!  Works:

***@***.***

**Comment by norman-wong-cn** [comment]
I am sorry to bother you, but I don’t understand why this error message occurs.

I have added the new JAR file to driver in Postgresql:
***@***.***

Setup ADC:
***@***.***

Configured the JDBC URL:
jdbc:postgresql:///postgres?cloudSqlInstance=cnr-daasscdhsql-npd-u28f:northamerica-northeast1:gne1scdhpgd01d&ipTypes=PRIVATE&socketFactory=com.google.cloud.sql.postgres.SocketFactory&ENABLE_IAM_AUTH=true
***@***.***


Error:
***@***.***
Shouldn’t the socket factory driver be retrieving the Oath2 token based on the ADC credentials?

I am able to connect using cloud_sql_proxy, but I would rather use the socket factory to avoid having to managing cloud_sql_proxy processes locally.

Thanks,
Norm Wong

**Comment by ttosta-google** [comment]
I don't see the error message.

Please use `enableIamAuth=true` in your JDBC url.

If the issue persists, please create a new issue.

**Comment by norman-wong-cn** [comment]
Please update your documentation, I was referencing this:
***@***.***

This should be in camel case as described in your email below.  I was using the documented uppercase property.

With your update it works perfectly.  Thanks for all your work!

Norm

**Comment by ttosta-google** [comment]
PR https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/1798 created. Thanks for the suggestion.
