### ISSUE TITLE
Update Spring Cloud GCP Configuration Parameters

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#2065]
We should update [Spring Cloud GCP configuration parameters](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/1840ffc5005cf645bcb507e4d3394ae80f7dd718/docs/src/main/asciidoc/sql.adoc#cloud-sql-configuration-properties) to include new features such as `PSC` as an ip-type and a lazy refresh param to enable lazy refresh mode, etc.

**Comment by hessjcg** [comment]
I've sent a PR to spring-cloud-gcp to address this issue. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3286

**Comment by hessjcg** [comment]
The PR to spring-cloud-gcp issue is merged. See https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3286 

Additional PSC and other parameters will be available in the next release of Spring Cloud GCP 

I'm closing this as fixed.

**Comment by jackwotherspoon** [comment]
Just for additional clarity, these will be available in `v5.9.0` of spring-cloud-gcp 

Ref: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3351
