### ISSUE TITLE
Is Spring Boot 2.7.16 compatible with socket factory 1.20.1?

### ISSUE THREAD

**Issue by julie0005** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#2069]
### Question

Is Spring Boot 2.7.16 compatible with socket factory 1.20.1?
Recently, our service got errors related to Issue #2059 , and I was trying to update library version from 1.12.0 to 1.20.1.
However, we got errors about compatibility.
I would appreciate if you let me know about any references telling about libraries-bom and socket-factory correct version info.

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.google.cloud.sql.core.InternalConnectorRegistry.createConnector(InternalConnectorRegistry.java:311)

The following method did not exist:

    com.google.auth.oauth2.GoogleCredentials.getUniverseDomain()Ljava/lang/String;

The calling method's class, com.google.cloud.sql.core.InternalConnectorRegistry, was loaded from the following location:

    jar:file:/Users/binaryfoo/.m2/repository/com/google/cloud/sql/jdbc-socket-factory-core/1.20.1/jdbc-socket-factory-core-1.20.1.jar!/com/google/cloud/sql/core/InternalConnectorRegistry.class

The called method's class, com.google.auth.oauth2.GoogleCredentials, is available from the following locations:

    jar:file:/Users/binaryfoo/.m2/repository/com/google/auth/google-auth-library-oauth2-http/1.16.0/google-auth-library-oauth2-http-1.16.0.jar!/com/google/auth/oauth2/GoogleCredentials.class

The called method's class hierarchy was loaded from the following locations:

    com.google.auth.oauth2.GoogleCredentials: file:/Users/binaryfoo/.m2/repository/com/google/auth/google-auth-library-oauth2-http/1.16.0/google-auth-library-oauth2-http-1.16.0.jar
    com.google.auth.oauth2.OAuth2Credentials: file:/Users/binaryfoo/.m2/repository/com/google/auth/google-auth-library-oauth2-http/1.16.0/google-auth-library-oauth2-http-1.16.0.jar
    com.google.auth.Credentials: file:/Users/binaryfoo/.m2/repository/com/google/auth/google-auth-library-credentials/1.16.0/google-auth-library-credentials-1.16.0.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.google.cloud.sql.core.InternalConnectorRegistry and com.google.auth.oauth2.GoogleCredentials

### Code

```Java
libraries-bom is the only thing we have in pom.xml that is related to google cloud.

<dependencyManagement>
        <dependencies>
            <dependency>
                <!-- Import dependency management from Spring Boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.7.16</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>libraries-bom</artifactId>
                <version>26.16.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by jackwotherspoon** [comment]
Hi @julie0005 thanks so much for raising a separate issue here on the Cloud SQL Java Connector 😄 

> The following method did not exist:
> ```
> com.google.auth.oauth2.GoogleCredentials.getUniverseDomain()Ljava/lang/String;
> ```

You need to bump your version of the `google-auth-library-oauth2-http` as the method that does not exist was added in [`v1.21.0 `](https://github.com/googleapis/google-auth-library-java/blob/main/CHANGELOG.md#1210-2023-12-21) of the dependency and you seem to be using `v1.16.0`.

I would recommend bumping the `google-auth-library-oauth2-http` dep to `v1.24.1` as that is what we currently use:

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/1c4e60c9bd067c5f14f82f930544fee0caedd4b5/pom.xml#L176

This should resolve your issue for you, keep me posted if it does not and I can help further 😄

**Comment by julie0005** [comment]
We don't have seperate dependency of 'google-auth-library-oauth2-http', the only dependencies we have about 'gcp' is 'library-bom'. So, it is hard to only change the version 'google-auth-library-oauth2-http'. I think I need appropriate version of library-bom with socket factory 1.20.1

**Comment by julie0005** [comment]
It is solved. Thanks!
