### ISSUE TITLE
R2DBC Connection URL doesn't work when using //google/

### ISSUE THREAD

**Issue by pcthomatos** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#285]
## Question
What's your question? Please provide as much relevant information as possible
to reduce turnaround time. 

Hello I'm trying to use the newly introduced **socketFactory** for **R2DBC** it seems to work locally when I connect to a gcp database **but only when I point to the database's ip address**

>     url: r2dbc:postgresql://xxx.xxx.xxx.xxx/<DATABASENAME>?cloudSqlInstance=<INSTANCENAME>&socketFactory=com.google.cloud.sql.postgres.SocketFactory

When I try to use the traditional way with **google**, it doesn't work

>     url: r2dbc:postgresql://google/<DATABASENAME>?cloudSqlInstance=<INSTANCENAME>&socketFactory=com.google.cloud.sql.postgres.SocketFactory

I get this error:

>     Caused by: io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to google:5432 at io.r2dbc.postgresql.PostgresqlConnectionFactory.cannotConnect(PostgresqlConnectionFactory.java:222) at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3284) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at reactor.core.publisher.Mono.subscribe(Mono.java:4218) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at reactor.core.publisher.Mono.subscribe(Mono.java:4218) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.onError(MonoDelayUntil.java:175) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185) at reactor.netty.resources.NewConnectionProvider$DisposableConnect.operationComplete(NewConnectionProvider.java:160) at reactor.netty.resources.NewConnectionProvider$DisposableConnect.operationComplete(NewConnectionProvider.java:106) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183) at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) at reactor.netty.resources.NewConnectionProvider.lambda$acquire$0(NewConnectionProvider.java:79) at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) at reactor.core.publisher.Mono.subscribe(Mono.java:4218) at reactor.core.publisher.Mono.subscribeWith(Mono.java:4329) at reactor.core.publisher.Mono.subscribe(Mono.java:4189) at reactor.core.publisher.Mono.subscribe(Mono.java:4125) at reactor.pool.SimplePool.drainLoop(SimplePool.java:201) at reactor.pool.SimplePool.drain(SimplePool.java:172) at reactor.pool.SimplePool.doAcquire(SimplePool.java:132) at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:351) at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:130) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:76) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:69) at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:163) at reactor.pool.SimplePool$QueueBorrowerMono.subscribe(SimplePool.java:323) at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:110) at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:94) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214) at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:396) at reactor.pool.SimplePool.lambda$drainLoop$7(SimplePool.java:206) at reactor.core.publisher.LambdaMonoSubscriber.doError(LambdaMonoSubscriber.java:152) at reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:147) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at reactor.core.publisher.Mono.subscribe(Mono.java:4218) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at reactor.core.publisher.Mono.subscribe(Mono.java:4218) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at reactor.core.publisher.Mono.subscribe(Mono.java:4218) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.onError(MonoDelayUntil.java:175) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185) at reactor.netty.resources.NewConnectionProvider$DisposableConnect.operationComplete(NewConnectionProvider.java:160) at reactor.netty.resources.NewConnectionProvider$DisposableConnect.operationComplete(NewConnectionProvider.java:106) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109) at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89) at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:214) at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46) at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180) at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:984) at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504) at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417) at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.net.UnknownHostException: google at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797) at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505) at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364) at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298) at java.base/java.net.InetAddress.getByName(InetAddress.java:1248) at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156) at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153) at java.base/java.security.AccessController.doPrivileged(Native Method) at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153) at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41) at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61) at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206) at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162) at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116) at reactor.netty.resources.NewConnectionProvider.lambda$acquire$0(NewConnectionProvider.java:73) ... 94 common frames omitted

**Is this the correct way to enter the url? Is this feature not available yet?**

**Comment by kurtisvg** [comment]
It looks like the driver format should be something like this:
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/91de5c72214df2103318bcc567f976c5f08a753e/r2dbc-postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIntegrationTests.java#L48

**Comment by pcthomatos** [comment]
Keep in mind that this connection string works:
>     url: r2dbc:postgresql://xxx.xxx.xxx.xxx/<DATABASENAME>?cloudSqlInstance=<PROJECT_ID>:<REGION_ID>:<INSTANCE_ID>&socketFactory=com.google.cloud.sql.postgres.SocketFactory

I tried the suggestion above using 
>     r2dbc:gcp:postgres://user:password@<PROJECT_ID>:<REGION_ID>:<INSTANCE_ID>/dbName 

But now this error is returned:

>     An exception reactor.core.Exceptions$BubblingException: io.netty.channel.ChannelPipelineException: io.r2dbc.postgresql.client.SSLTunnelHandlerAdapter.handlerAdded() has thrown an exception; removed. at reactor.core.Exceptions.bubble(Exceptions.java:173) at reactor.core.publisher.Operators.onErrorDropped(Operators.java:612) at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onError(ReactorNettyClient.java:845) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:196) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:425) at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:211) at reactor.netty.channel.FluxReceive.onInboundError(FluxReceive.java:413) at reactor.netty.channel.ChannelOperations.onInboundError(ChannelOperations.java:436) at reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:129) at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:623) at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) at io.netty.channel.DefaultChannelPipeline$6.run(DefaultChannelPipeline.java:1141) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: io.netty.channel.ChannelPipelineException: io.r2dbc.postgresql.client.SSLTunnelHandlerAdapter.handlerAdded() has thrown an exception; removed. at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:624) ... 9 more Caused by: java.lang.NullPointerException at io.r2dbc.postgresql.client.SSLTunnelHandlerAdapter.handlerAdded(SSLTunnelHandlerAdapter.java:36) at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ... 9 more was thrown by a user handler's exceptionCaught() method while handling the following exception: io.netty.channel.ChannelPipelineException: io.r2dbc.postgresql.client.SSLTunnelHandlerAdapter.handlerAdded() has thrown an exception; removed. at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:624) at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) at io.netty.channel.DefaultChannelPipeline$6.run(DefaultChannelPipeline.java:1141) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.NullPointerException: null at io.r2dbc.postgresql.client.SSLTunnelHandlerAdapter.handlerAdded(SSLTunnelHandlerAdapter.java:36) at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ... 9 common frames omitted

**Comment by kurtisvg** [comment]
Unfortunately I don't have much experience with the r2dbc interface, so I'm not sure what's going on here.

@shubha-rajan, @dmitry-s - Any ideas?

**Comment by shubha-rajan** [comment]
That first connection string works because it's not using the gcp connection factory and is connecting directly to the database with the IP address. The `cloudSqlInstance` and `socketFactory` args are likely being ignored.  

As for the error you're seeing, according to the stack trace, the root problem is a Null Pointer Exception somewhere. Your updated connection string format looks right, so I'm thinking the error has to do with either your connection code or with your dependencies. Can you post a code snippet of when you get a connection using the URL?

**Comment by shubha-rajan** [comment]
For reference, here's a working example of connecting with the postgres r2dbc connector:
```java
    String r2dbcURL = String
        .format("r2dbc:gcp:postgres://%s:%s@%s/%s", DB_USER, DB_PASSWORD, CONNECTION_NAME,
            DB_NAME);

      ConnectionFactory connectionFactory = ConnectionFactories.get(r2dbcURL);

      Mono.from(connectionFactory.create())
          .flatMap(conn -> Mono.from(conn.createStatement("SELECT 1").execute())
              .doOnTerminate(() -> Mono.from(conn.close()).subscribe()))
          .block();
```
Note that you have to include the `r2dbc-postgres` dependency along with the r2dbc connector:
```xml
    <dependency>
      <groupId>com.google.cloud.sql</groupId>
      <artifactId>cloud-sql-connector-r2dbc-postgres</artifactId>
      <version>1.1.0</version>
    </dependency>
    <dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-postgresql</artifactId>
    <version>0.8.5.RELEASE</version>
```

**Comment by pcthomatos** [comment]
I see the error of my ways.

I was using

```xml
    <dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-postgresql</artifactId>
    <version>0.8.4.RELEASE</version>
```

Using **0.8.5** fixed everything and it's working in GCP. 
Thank you!
