### ISSUE TITLE
Improve document on how to work w/ ConnectorJ 5 vs 6

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#29]
README calls out using a special dependency when working w/ Connector J 6
> Note: If you wish to use the 6.x (development) version of the MySQL driver, use the artifact id 'mysql-socket-factory-connector-j-6'.

But it appears to be under the Gradle section, which could be easily missed w/ Maven users.

This can be more prominent if called out under a new heading.

**Comment by laixer** [comment]
I made the note more prominent. What do you think?
