### ISSUE TITLE
Add documentation on using a service account JSON file

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#32]

**Comment by Kool-Koder** [comment]
Hi is there any update regarding this? I am attempting to connect using a service account JSON file instead of the application-default credentials but to no avail. Thanks!

**Comment by kurtisvg** [comment]
Closing - currently only authentication is only possible through the [Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials), in which the documentation provides examples of using a service account via a json file.

If you want to follow progress on adding external credentials, please follow #66.
