### ISSUE TITLE
Dataproc clusters not being able to connect to Cloud SQL

### ISSUE THREAD

**Issue by manualaman5** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#349]
## Description
We faced an issue when trying to connect from Dataproc to CloudSQL using socket factory. The error was originated when invoking "jdbc()" method on a DataFrameReader object bundled as part of standard Spark 2.3.4 framework.
The error thrown was java.sql.SQLNonTransientConnectionException: Cannot connect to MySQL server on localhost.

## Solution
There should be some tips on this documentation, so it can lead to the solution. The solution to the problem was the following:
Jarfile downloaded on all the worker nodes.

**Comment by kurtisvg** [comment]
@manualaman5 I'm not very familiar with Dataproc, but if you want to submit a PR feel free to add it under [Additional Information](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#additional-information) in the README.
