### ISSUE TITLE
Add support for IAM database authentication

### ISSUE THREAD

**Issue by redbaron** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#350]
## Feature Description
Add support for IAM database authentication: https://cloud.google.com/sql/docs/postgres/authentication

## Additional Context

New IAM database authentication requires fetching new access token before initiating a new connection. It makes it tricky to use with connection pooling, because password cannot be set upfront.  Socket factory is called to establish a new connection, so it is well positioned to request fresh access tokens on every connection.

**Comment by kurtisvg** [comment]
This is currently on our roadmap - however it's awaiting some backend changes before the SocketFactory can support it.
