### ISSUE TITLE
Update SQL Server documentation in README

### ISSUE THREAD

**Issue by Paul-Hoke** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#373]
It looks like SQL Server JDBC support was added in 1.2.0.

Dependency info for SQL Server is included under "Add library as a dependency" but there is no info for SQL Server under "Creating the JDBC URL"

I have added the SQL Server JDBC dependency and have done my best to guess what the correct JDBC URL should be but have been unable to successfully connect.  So i'm not sure if I'm wrong or there is possibly a bug

FYI Example of JDBC URL I am attempting to use: `jdbc:sqlserver:///<DATABASE_NAME>;socketFactory=com.google.cloud.sql.sqlserver.SocketFactory;cloudSqlInstance=<INSTANCE_CONNECTION_NAME>;user=<USER_NAME>;password=<PASSWORD>`

**Comment by shubha-rajan** [comment]
hi @Paul-Hoke. Looking at the connection properties [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15) and the documentation on forming a connection URL [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15), the connection URL should probably look something like:
`jdbc:sqlserver://localhost;databaseName=<DATABASE_NAME>;socketFactoryClass=com.google.cloud.sql.sqlserver.SocketFactory;socketFactoryConstructorArg=<INSTANCE_CONNECTION_NAME>;user=<USER_NAME>;password=<PASSWORD>`.

Try that and if it works, I'll make a PR to add it to the documentation.

**Comment by Paul-Hoke** [comment]
Hey @shubha-rajan, thanks for your assistance on this - I finally figured out the root cause here, hopefully this will be helpful for others.  It still might be worth updating the docs with an official JDBC URL example.

**Project setup:**  My project is a Java 8 project so I was using the `mssql-jdbc/8.4.1.jre8` maven dependency to access the `com.microsoft.sqlserver.jdbc.SQLServerDriver`.  

This combination WILL NOT work currently with the cloud socket factory.  Even with cloud-proxy running I always received `Connection Failed TCP / IP to localhost port 1433` .  Other methods of accessing the cloud database from my local machine worked fine (DBeaver / SQL Server Management Studio / sqlcmd) so it was hard for me to believe that this was a cloud firewall issue.

**Solution**  Remove `mssql-jdbc` and replace with the latest `jtds` dependency and switch JDBC Driver to `net.sourceforge.jtds.jdbc.Driver`

The JDBC URL provided above appears to be in the correct format when using the `SQLServerDriver` but needs to be slightly changed to accommodate the jtds Driver.  The beginning of the URL needs to start with `jdbc:jtds:sqlserver` instead of `jdbc:sqlserver`

**Comment by shubha-rajan** [comment]
> **Project setup:** My project is a Java 8 project so I was using the `mssql-jdbc/8.4.1.jre8` maven dependency to access the `com.microsoft.sqlserver.jdbc.SQLServerDriver`.

Okay, that explains it. The minimum version of `mssql-jdbc` that's supported is 9.1.0. 8.4.1 is incompatible.
