### ISSUE TITLE
Not able to connect to Cloud SQL using Java SocketFactory Library

### ISSUE THREAD

**Issue by asktushar88** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#40]
I am trying to connect to Cloud SQL ( Mysql ) using my java code. I am getting the below error -

```
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create socket factory 'com.google.cloud.sql.mysql.SocketFactory' due to underlying exception: 
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.sql.mysql.SocketFactory
```
I am running the above command using the JAR build from Maven  (clean compile assembly:single) on my google shell 
Any help would be appreciated. Thanks in advance. 

Posted my complete code here - 
https://stackoverflow.com/questions/45054519/not-able-to-connect-to-cloud-sql-using-java-socketfactory-library

**Comment by laixer** [comment]
This is an issue with how you're packaging the application, it is not related at all to this. Thus Stackoverflow is a better place for this question. 

There's likely an issue with the way you configured the assembly plugin. You can verify this yourself by opening the jar file, it is likely that none of the dependencies are included there. Please update your stackoverflow question to include the snippet of your pom.xml file describing how you have configured the assembly plugin.

**Comment by asktushar88** [comment]
Hi, 

I opened the JAR file manually, and all the dependencies are available inside the JAR. 

I have added MYSQL Socket factory and MYSQL Connector both as mentioned in my JAR. 

Do you think, there can be anything else ? 

Thanks in advance.
