### ISSUE TITLE
New connections print out INFO level log

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#42]
```
c.g.cloud.sql.mysql.SslSocketFactory     : Connecting to Cloud SQL instance [spring-cloud-gcp:us-central1:book-store] on IP [35.184.73.37].
```

When used in a connection pool, the logs can be extensive. Regular MySQL connections don't print info level log like this. Recommend lowering the level to DEBUG or TRACE.

**Comment by laixer** [comment]
What do you think about logging at INFO for the first connection and logging the rest at a lower level? 
I think it's useful for troubleshooting if the first connection fails, but less interesting after that.

**Comment by saturnism** [comment]
@laxier agreed on the approach. Thanks!

**Comment by jc25560** [comment]
Hi @kurtisvg. A suggestion to reduce logging was suggested by @vadimberezniker but the source code for logging "Connecting to Cloud SQL instance" has remained unchanged. Is there any plan to reduce this logging or was this issue dropped?

**Comment by kurtisvg** [comment]
@jc25560 It looks like I closed this issue for being stale back when the repo changed owners. You are welcome to open a new issue if you'd like to see this change happen. 

My initial thought is that the logs can be useful in tracking connection management, and shouldn't be happening very frequently (typically apps are using 1-25 connections over a default 8 hour lifetime). IIRC, the socketfactory also uses its own logger, so you can probably just change the log level for it specifically.

**Comment by jc25560** [comment]
Thanks for that feedback!
Hikari connection pool has a default maximum connection lifetime of 30 minutes, which was why I was seeing this get logged more frequently than expected. Changing the Hikari config resolved this.
