### ISSUE TITLE
Compatibility with Google Cloud Dataproc

### ISSUE THREAD

**Issue by martinstuder** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#45]
There are compatibility issues with Google Cloud Dataproc. Specifically, Apache Spark 2.2.0 on Dataproc 1.2 uses jackson-core v2.6.5 while the current version of mysql-socket-factory (v1.0.4 as of writing) transitively depends on jackson-core v2.1.3.
What is the recommended way of using mysql-socket-factory with Google Cloud Dataproc (in order to connect to Google Cloud SQL)? For now I simply removed the jackson-core dependency from mysql-socket-factory which seemed to work fine so far ...

**Comment by laixer** [comment]
I don't have a good answer for you. The Jackson dependency comes from the Google API library, not directly from this library. I could add an explicit dependency from this library on a newer version of Jackson, but I'm sure we would then get complaints from people who need an older version... 

What you have done seems like a reasonable way to address the problem.
