### ISSUE TITLE
Minor: provide consistency across MySQL|PostgreSQL JDBC connection URLs

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#49]
It's a minor point but:

* MySQL uses `cloudSqlInstance` whereas PostgreSQL uses `socketFactoryArg`
* Recommend these be consistent and more accurately be called `cloudSqlConnection`

In both cases, the property value required is the project-id:region:instance-id value and not the instance (id|name) so this could be confusing.

The MySQL JDBC URL requires `cloudSqlInstance`:
```jdbc:mysql://google/[[DATABASE-NAME]]?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=[[CONNECTION-NAME]]```

The PostgreSQL JDBC URL requires `socketFactoryArg`:
```jdbc:postgresql://google/[[DATABASE-NAME]]?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=[[CONNECTION-NAME]]```

**Comment by laixer** [comment]
Postgres driver doesn't support custom property names, otherwise we would have made them consistent.
