### ISSUE TITLE
Publish bill-of-materials (BOM)?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#499]
## Feature Description

It's nice to have bill-of-materials (https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms) of this repository's libraries published to Maven Central.

## Alternatives Considered

Users can specify individual libraries in their pom with their versions. It's prone to dependency conflicts.

## Additional Context

I'm one of the maintainers of the [Google Cloud Platform Libraries BOM](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM) (Libraries BOM) and there's a discussion about whether to include the cloud sql jdbc socket factory libraries in the BOM. 

https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/2073

The Google Cloud customers using the BOM would have less Java dependency conflicts, because we monitor dependency conflicts in the BOM. If there's dependency conflicts between a library in this repository and another Google Cloud library, we can proactively work together to fix the problem.

A BOM can import another BOM. If we decide to include cloud-sql-jdbc-socket-factory libraries in the Libraries BOM, it's easier for us to maintain the versions through cloud-sql-jdbc-socket-factory's BOM.

**Comment by kurtisvg** [comment]
I'm fine with adding a BOM - I know we discussed it a few years ago. I'm a little unsure of where in the dependency graph this library should fall (and thus, what should be in our BOM, and which BOMs we should be in). 

Do we have any guidance around this?

**Comment by suztomo** [comment]
Your BOM should contain the artifacts published by this repository.

**Comment by shubha-rajan** [comment]
For now, we've decided to hold off on adding a BOM. We'll reopen this issue if it becomes necessary
