### ISSUE TITLE
Establishing SSL connection without server's identity verification is not recommended.

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#50]
Using the [sample JDBC URL](https://cloud.google.com/sql/docs/mysql/connect-external-app#java), I'm seeing warnings when opening new connections:

```
Thu Aug 24 16:12:30 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

Does it matter if the connection contains `useSSL=true|false` since we're using the tunnel? What is the guidance from the Cloud SQL team on using this?

The published sample JDBC URL should probably also be changed to contain `&useSSL=true` or `false`.

**Comment by laixer** [comment]
I would recommend setting useSSL=false since it's redundant and less optimal to use SSL at the MySQL level since the entire connection is already within an SSL tunnel.

We'll update the docs to that effect.

**Comment by kurtisvg** [comment]
Closing - `useSSL=false` is already suggested in the docs both here and on the cloud site.
