### ISSUE TITLE
postgresql connection error from app engine when adding postgis library

### ISSUE THREAD

**Issue by orloffmarket** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#51]
When I add the postgis-jdbc dependency to my maven conf, eg

```
    <dependency>
      <groupId>net.postgis</groupId>
      <artifactId>postgis-jdbc</artifactId>
      <version>2.2.1</version>
    </dependency>
```

My connection fails on init (jdbc:postgresql://google/mydbname) as it doesn't recognize "google" as a hostname.  

I tried several versions, is there one known to work with cloud sql ?

**Comment by laixer** [comment]
Interesting. It works fine if you remove this dependency?

**Comment by laixer** [comment]
I had a brief look at the postgis-jdbc source code and I don't see anything obvious that should break this library.

Can you confirm that you are able to connect successfully w/o this dependency?
Can you provide a code samples that demonstrates how you are constructing the JDBC URL?

**Comment by orloffmarket** [comment]
Yes if I remove the dependency then it works fine.  I've confirmed this behavior making only that 1 change.  I'm basically using this demo 

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/flexible/postgres

Same exact method of connecting, and I don't change anything but add the postgis dependency and the connection string fails.  I'm guessing there's some jdbc code that Google is inserting into the driver and when I use the postgis extension it pulls in the native jdbc driver which fails, but that's just a guess.

**Comment by laixer** [comment]
Strange, this library is using the standard hooks in the Postgres driver to specify a custom socket library (the URL has ?socketFactoryArg=INSTANCE_CONNECTION_NAME&socketFactory=com.google.cloud.sql.postgres.SocketFactory).
Seems that postgis-jdbc must be breaking this somehow.

**Comment by orloffmarket** [comment]
Yes I'm totally stumped.  Trying to work up a minimal reproduction of the issue with that example codebase above.  Will push the minimal example shortly.

**Comment by orloffmarket** [comment]
I am using the custom socket library per your comment.  It works fine locally.  Also works fine if I remove the postgis library and related imports.  Really stumped on this one.

**Comment by laixer** [comment]
You mean it works locally even with postgis? Only doesn't work when deployed?

**Comment by orloffmarket** [comment]
That is correct.  Although now I am unable to reproduce with my latest test.  This is so weird.  Trying to put up a solid minimal example now.  And of course its working instead.

**Comment by orloffmarket** [comment]
Well I can't reproduce and its working now.  Going to close this until I can reproduce again, hopefully never.  Thanks for your input everyone.

**Comment by laixer** [comment]
Ok. Please reopen with a repro if you are able to reproduce it again.
