### ISSUE TITLE
Reduce initial connection time

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#53]
it appears the startup is dependent on requesting a temporary cert.  does this reuse the cert? In a typical deployment w/ a connection pool, 10 or 20 connections may start in parallel. will each new connection request a new cert?

is there a way to generate a cert and force use the pre-generated cert?

thanks!

**Comment by kurtisvg** [comment]
This was fixed in #142
