### ISSUE TITLE
Verify OAuth scope required by API and document

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#54]
While specifying our credential factory through the `cloudSql.socketFactory.credentialFactory` environment variable, we used to use the SQL Admin scope (https://www.googleapis.com/auth/sqlservice.admin).

Since we're not doing region discovery anymore, we don't need this scope and want to get rid of it. It sounds like the correct scope to use now is https://www.googleapis.com/auth/cloud-platform, but this doesn't appear to be documented anywhere here, https://cloud.google.com/sql/docs/mysql/connect-external-app or in https://developers.google.com/identity/protocols/googlescopes.

We should probably add documentation to all these places mentioning the correct scope to use.

**Comment by kurtisvg** [comment]
Closing this. I believe SQL Admin scope is required for the ephemeral certificate creation.
