### ISSUE TITLE
Default PROJECT-ID in 'cloudSqlInstance' if not specified

### ISSUE THREAD

**Issue by dansiviter** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#555]
## Feature Description
To reduce the verbosity of configuration and permit more environment parity, if no `PROJECT-ID` is specified in the ` PROJECT-ID:REGION:INSTANCE-ID` connection name, derive it from the metadata server to the same project at the VM. Potential ways of defining this could be:
 * Empty: `:REGION:INSTANCE-ID`,
 * Placeholder: `<defaultProjectId>:REGION:INSTANCE-ID`.

## Alternatives Considered
No generic workarounds.

## Additional Context
Value could be extracted from `ServiceOptions#getDefaultProjectId`.

**Comment by enocom** [comment]
Closing this. I think we always want to require the instance connection name as that’s what Cloud SQL anchors on and what all the other connectors use too.
