### ISSUE TITLE
Cannot connect to SQL instance from Intellij on WSL2

### ISSUE THREAD

**Issue by stefda** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#612]
## Bug Description

I am trying to connect from Intellij to my Cloud SQL Postgres instance via Cloud SQL Proxy. When I set up the connection as instructed and run the proxy, I get the following error on connection test:

```
[99999] Something unusual has occurred to cause the driver to fail. Please report this exception. com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden GET https://sqladmin.googleapis.com/sql/v1beta4/projects/c9n-product/instances/europe-west1~platform-postgresql-demo { "code": 403, "errors": [ { "domain": "global", "message": "The client is not authorized to make this request.", "reason": "notAuthorized" } ], "message": "The client is not authorized to make this request." }.
```

## How to reproduce

1. download and install `cloud_sql_proxy` as instructed [here](https://cloud.google.com/sql/docs/mysql/sql-proxy#linux-64-bit)
2. download postgres-socket-factory-1.3.3-jar-with-driver-and-dependencies.jar and add it to Driver files in PostgreSQL driver in Intellij
3. configure connection URL with `jdbc:postgresql:///api?cloudSqlInstance=<project-id>:<zone>:<instance-id>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=<password>`
4. `gcloud auth application-default login` with an account that is the owner of the cloud organisation and project
5. run `./cloud_sql_proxy -dir ~/.cloud-sql/sockets` on WSL2 that correctly prints `Listening on...` for each SQL instance
6. click Test connection in Intellij which throws the error above

## Environment

1. OS type and version: Windows 10, WSL2
2. Socket Factory version: postgres-socket-factory-1.3.3-jar-with-driver-and-dependencies.jar

**Comment by stefda** [comment]
Doing a bit more digging, I suspect this is caused by the fact a Windows Intellij instance cannot establish a connection to db via socket. I'll leave the issue open in case I'm wrong, but I'm afraid this is a dead end.

**Comment by enocom** [comment]
Caveat: I have only done this with IntelliJ on Linux, but it has worked.

In theory, you can connect to a Cloud SQL instance using either the proxy OR the socket factory. In my experience, the socket factory works well, and you can avoid using the Unix socket.

Seems like you have a lot of the steps right already, but for reference here are some nice docs:

https://www.jetbrains.com/help/datagrip/connect-to-google-cloud-sql-instances.html#configuring-connections-with-the-cloud-sql-connector-for-java

**Comment by enocom** [comment]
Will you report back and let us know if the instructions above worked for you?

**Comment by stefda** [comment]
Ah fantastic, couldn't find the docs (didn't think of looking at DataGrip!) but will give it a try soon and report back.

**Comment by stefda** [comment]
I can confirm that following the jetbrains [docs for setting up Cloud SQL connection](https://www.jetbrains.com/help/datagrip/connect-to-google-cloud-sql-instances.html#configuring-connections-with-the-cloud-sql-connector-for-java) worked as expected. I can now connect to my SQL instance using both TCP and sockets from Intellij.

I believe that the important step that I missed was going into Advanced connection settings and adding `socketFactory = com.google.cloud.sql.postgres.SocketFactory`.

Thank you for the link, hope this helps someone!

**Comment by enocom** [comment]
I'll add a link in the README for future readers who are trying to do the same. Glad the instructions worked.
