### ISSUE TITLE
The connection to the database server is faster to connect via socketFactory than to connect via IP.

### ISSUE THREAD

**Issue by Kevin2iBi** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#63]
I will have an increase in perfomance if I connect my application via socketFactory than connect directly via ip ???

**Comment by kurtisvg** [comment]
If using the socket factory from GAE Standard, using the socket factory will allow you use use a Unix Domain socket, which is a performance improvement. 

If using the socket factory from other runtimes it will use a TCP/IP socket, but will not require you to white list an IP. This means the socket factory is more secure.
