### ISSUE TITLE
Allow external GoogleCredentials authentication 

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#66]
`new SQLAdmin.Builder()` requires a `HttpRequestInitializer` as its third argument, not necessarily `Credential` which `createAdminApiClient()` requests.

This would be useful because, for example, on our Spring integrations, we want to pass in-memory credentials from a pre-existing `GoogleCredentials` object (from the newer `google-auth-library-java` library).
As I understand, the recommended way to use them is to use a [`HttpCredentialsAdapter`](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java), which is a `HttpRequestInitializer` but not `Credential`.
I also haven't found any way to conveniently generate a `Credential` from a `HttpCredentialsAdapter`.

We would also need to pass in a `HttpRequestInitializer` instead of a `CredentialFactory` in the `CredentialFactory.CREDENTIAL_FACTORY_PROPERTY` property.

**Comment by bhtucker** [comment]
This would also be useful for Cloud Partners engineering applications. We too have pre-existing `GoogleCredentials` that users created from (their choice of) application default credentials or a service account file.

**Comment by Luttik** [comment]
I would also really like this option, messing with environment variables doesn't seem like a smart thing to do. And I don't really understand while virtually every google system has the option to use in-memory credentials but not the SQL service.

**Comment by nickmarx12345678** [comment]
I'm also trying to understand how we can achieve configure CloudSQL auth connections without using an env var, any examples?

**Comment by hstonec** [comment]
I was wondering if there is any update about this issue? 

We also would like to use our own credential instead of ADC to initialize the client, but realized that we have to use the deprecated `com.google.api.client.googleapis.auth.oauth2.GoogleCredential` to create the credential because `com.google.cloud.sql.CredentialFactory.create()` requires `com.google.api.client.auth.oauth2.Credential` instead of `com.google.auth.Credentials` which is recommended in https://github.com/googleapis/google-auth-library-java.

**Comment by kurtisvg** [comment]
So this is a bit tricky to do, but I think it could be done by adding a static method to [SocketFactory](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java) class. This method would essentially take an instance connection name and a credential, and could be used create the CloudSQLInstance class with the correct credentials set on the SQLAdmin API. 

We would need to be careful to cleanup any previous CloudSQLInstance objects and refresh threads if a new one is set overtop.

**Comment by yorkyu-mercari** [comment]
Simplest workaround should be create a Factory class and use it to create HttpRequestInitializer

```
System.setProperty(CredentialFactory.CREDENTIAL_FACTORY_PROPERTY, ServiceAccountCredentialFactory.getClass.getName)
```

I am using scala so the test code will be like
```
class ServiceAccountCredentialFactory extends CredentialFactory {
  override def create(): HttpRequestInitializer = {
    val jsonPath: String = System.getProperty(CREDENTIAL_FILE_PATH)
    var credentials: GoogleCredentials = GoogleCredentials.fromStream(new FileInputStream(jsonPath))

    if(credentials.createScopedRequired()) {
      credentials = credentials.createScoped(Seq(
        SQLAdminScopes.SQLSERVICE_ADMIN,
        SQLAdminScopes.CLOUD_PLATFORM
      ).asJava)
    }
    new HttpCredentialsAdapter(credentials)
  }
}
```

**Comment by shubha-rajan** [comment]
https://github.com/googleapis/google-auth-library-java/pull/658 exposed a getter that returns a`Credentials` object. Using that getter along with the extended factory class above should allow you to use external GoogleCredentials in your application.

**Comment by kurtisvg** [comment]
Going to mark this as closed. I think this current journey is already possible with the current interface.
