### ISSUE TITLE
Document how to use from IntelliJ IDEA's database query tool

### ISSUE THREAD

**Issue by stickfigure** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#74]
For the life of me I can't figure out how to get this working from IntelliJ. I'm using the same query string that my app does, but there seems to be a classpath issue.

I've added `postgres-socket-factory-1.0.8.jar` and `jnr-unixsocket-0.18-jar-with-dependencies.jar` to my "Driver files" classpath, but I still get "[08006] The SocketFactory class provided com.google.cloud.sql.postgres.SocketFactory could not be instantiated." How can I debug this?

**Comment by DhiralKaniya** [comment]
+1
Same issue I am facing with a Spring-boot application.

**Comment by kurtisvg** [comment]
@meltsufin - do you have any insight on how to do this with intellij?

**Comment by meltsufin** [comment]
@stickfigure @DhiralKaniya We have a [Spring Boot sample](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-sql-sample) that connects to Postgres without any problems. See if it works for you.

**Comment by stickfigure** [comment]
@meltsufin My application connects just fine... the problem is accessing the GUI database query tool that is built into IntelliJ IDEA. Getting the classpath set up seems to be a problem. Some sort of step-by-step instructions would be very helpful - IDEA's query tool is indispensable.

**Comment by kurtisvg** [comment]
@stickfigure I ran into the same issue - I'll see if I can investigate a little deeper and figure out what's going on. 

For a short-term workaround, have you tried using the proxy to connect instead? There are instructions [here](https://cloud.google.com/sql/docs/mysql/connect-admin-proxy) - you should be able to connect to it locally via the proxy without using this connector.

**Comment by meltsufin** [comment]
@dmitry-s was able to connect via IntelliJ IDEA. It involved building a fat-jar of the SocketFactory deps. He'll share the steps here.

**Comment by dmitry-s** [comment]
@stickfigure in order to connect via IntelliJ IDEA you would need to create a fat jar of postgres sub-project from https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory

To do that, add the following section to the postgress/pom.xml:
```
<build>
    <plugins>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>2.4.1</version>
        <configuration>
            <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
            </descriptorRefs>
        </configuration>
        <executions>
            <execution>
                <id>create-assembly</id>
                <phase>package</phase>
                <goals>
                    <goal>single</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
    </plugins>
</build>
```
Then, cd to postgres and run `mvn package`. This will produce postgres-socket-factory-1.0.10-SNAPSHOT-jar-with-dependencies.jar file in `target` directory.

Also, you need a postgres driver jar. You should add both jars to Driver files in the IntelliJ db connection configuration window, and use the following URL 

jdbc:postgresql://google/[DATABASE NAME]?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=[INSTANCE CONNECTION NAME]

**Comment by kurtisvg** [comment]
@meltsufin @dmitry-s Thanks for the help!

**Comment by stickfigure** [comment]
This worked, thanks!

Not sure if you want to consider the issue solved (as in "this issue is the documentation") or left open so it gets addressed in other documentation. I'll leave that up to you guys; having these instructions here is enough for me.

I hadn't thought about using the standalone proxy, but that's probably an even better solution.

**Comment by meltsufin** [comment]
Would it make sense to publish the fat jar to Maven Central as well to make it easier for other folks looking to do this?

**Comment by dmitry-s** [comment]
@stickfigure 
I am not sure if proxy would help. It creates a unix socket that you can use to connect with psql client, but AFAIK postgres jdbc driver can't connect to unix sockets.

**Comment by kurtisvg** [comment]
@dmitry-s - The proxy has options both for via unix socket and tcp port. This socket factory also support connection via unix socket. After #86, users will be able to force the connection through the unix socket via an environment variable if they wish. 

@meltsufin What's the standard policy for publishing a fat jar to maven central? Does it need to have a different version or package name?

**Comment by meltsufin** [comment]
I'm not sure, but it looks like it's not really a best practice based on [this SO thread](https://stackoverflow.com/questions/50179525/for-official-maven-repositories-do-people-release-fat-jars).
Maybe we can build and host the artifact on Google Storage instead? It would involve a manual step for updating it though.

**Comment by kurtisvg** [comment]
I've added them to the [release page](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases) for now.

**Comment by kurtisvg** [comment]
#89 to add instructions to the README.

**Comment by davinkevin** [comment]
Hello, 

I've red the documentation but I still have problem to connect to CloudSQL Postgresql from the database pane of IntelliJ.

I've configured the pane `additional files` in the `PostgreSQL` driver part like this : 
![image](https://user-images.githubusercontent.com/1970922/43186362-b82f7e36-8fee-11e8-92a1-d0dd68988075.png)

And created a `Project Data Sources`: 
![image](https://user-images.githubusercontent.com/1970922/43186695-be7cc888-8fef-11e8-9051-25619fba05ed.png)

And I finish every time in error. 😓

Do you have any additional information about this? I will do a PR with images to enhance the documentation if possible

**Comment by davinkevin** [comment]
I finally found the source of my problem, which was I use the `instance-name` instead of the `connectionName`. 

This line in example helps me : 
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/examples/postgres/compute-engine/src/main/java/com/google/cloud/sql/postgres/example/ListTables.java#L17

**Comment by Luttik** [comment]
Maybe this should be a seperate issue.

But I would like to use this approach on windows. I downloaded the fatjar from [maven (postgres-socket-factory)](http://central.maven.org/maven2/com/google/cloud/sql/postgres-socket-factory/1.0.12/postgres-socket-factory-1.0.12.jar). and [maven (unixsocket)](http://central.maven.org/maven2/com/github/jnr/jnr-unixsocket/0.21/jnr-unixsocket-0.21.jar).

But I still get `java.lang.ClassNotFoundException: jnr.unixsocket.UnixSocket` error. Im not sure if this is a windows issue or an issue with my setup.

**Comment by kurtisvg** [comment]
@Luttik The link you've provided is not to the jar-with-dependencies. You can find the jar-with-dependencies included on the  [Release's page](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases).

**Comment by Luttik** [comment]
I'm still having some problem with this. I think the issue might be that I'm trying to use it through the Intellij Idea database tool-view. Maybe the true issue is that I can't select com.google.cloud.sql.mysql.SocketFactory as main driver when making a custom configuration.

![screenshot](https://user-images.githubusercontent.com/6634187/52556402-b7c23280-2dec-11e9-82b5-3b72317838f5.png)

![capture](https://user-images.githubusercontent.com/6634187/52556703-9d3c8900-2ded-11e9-8272-7bec3de53ebe.PNG)
