### ISSUE TITLE
com.google.cloud.sql:postgres-socket-factory error in version 1.4.2 and version 1.4.3

### ISSUE THREAD

**Issue by nanoflow** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#741]
Hi, me and some of my team members have problem with the 
com.google.cloud.sql:postgres-socket-factory  throwing the following error when connection to a google cloud sql database is established:
```
Something unusual has occurred to cause the driver to fail. Please report this exception.
  com/google/cloud/sql/core/CoreSocketFactory
  com/google/cloud/sql/core/CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
```
Current work around: downgrade this library to version 1.4.1 in the following steps:
- in 'Edit Driver Settings' / 'Libraries'  click on Download/Update
- select Version 1.2.0 (or something very old) for the com.google.cloud.sql:postgres-socket-factory driver, check 'Force download / overwrite' and click Download
- restart dBeaver
- redo the above steps but with version 1.4.1

But still it would be nice, if the newest version could be a working one again

**Comment by nanoflow** [comment]
Problem occurs in DBeaver Community edition version Version 21.3.4.202202051448 on Ubuntu and MacOs

**Comment by kurtisvg** [comment]
Hey @nanoflow,

Any chance you can provide some more information: 

- Can you provide the full stack trace?
- Can you provide more information on your enviroment? JDK version, OS, etc? 
- Can you included steps to reproduce the problem?

**Comment by nanoflow** [comment]
this is the stack trace 

> > java.lang.ClassNotFoundException: com.google.cloud.sql.core.CoreSocketFactory
> 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
> 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
> 	at com.google.cloud.sql.postgres.SocketFactory.<clinit>(SocketFactory.java:42)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Unknown Source)
> 	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:46)
> 	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:39)
> 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:182)
> 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
> 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
> 	at org.postgresql.Driver.makeConnection(Driver.java:465)
> 	at org.postgresql.Driver.access$100(Driver.java:62)
> 	at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
> 	at java.base/java.lang.Thread.run(Unknown Source)

Session Data:

> eclipse.buildId=unknown
> java.version=11.0.12
> java.vendor=Eclipse Foundation
> BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
> Command-line arguments:  -os linux -ws gtk -arch x86_64

Steps to reproduce: 
install a fresh DBeaver, connect to a Google Cloud instance

**Comment by kurtisvg** [comment]
Hi @nanoflow - it doesn't look like that's the same error you posted above (and is still only a partial stack trace). This error seems to indiciate that you don't have the socketfactory installed.

**Comment by kurtisvg** [comment]
I've installed DBreaver and tried to connect and I'll I'm getting is the following:
```
Something unusual has occurred to cause the driver to fail. Please report this exception.
  com/google/cloud/sql/core/CoreSocketFactory
  com/google/cloud/sql/core/CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
```
The socket factory works fine on my machine (but DBeaver doesn't) so it seems like the problem is in DBeaver. I've opened a [bug here](https://github.com/dbeaver/dbeaver/issues/15459), feel free to chime in.

**Comment by kurtisvg** [comment]
Hey @nanoflow - I was able to fix this by following the advice here: https://github.com/dbeaver/dbeaver/issues/15459#issuecomment-1036261495

Adding the extra artifact caused everything to connect successfully.
