### ISSUE TITLE
Unable to connect to a MySQL Database if I use @ServletComponentScan Spring boot annotation

### ISSUE THREAD

**Issue by ManuelG28** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#768]
## Bug Description

I'm making a Slack Bot with Spring Boot, this application will be connected to a MySql database in Gcloud. I'm deploying this application in **Cloud run**. I made the configuration as google suggest [here](https://cloud.google.com/sql/docs/mysql/connect-run#java_1) and I set up my env variables as google suggest [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc-mysql.md#creating-thejdbc-url)
My issue is that if use `@ServletComponentScan` annotation in my main file, the connection will fail giving me an error like this:
 
`java.sql.SQLNonTransientConnectionException: Cannot connect to MySQL server on localhost:3,306.
Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also, make sure that the server has not been started with the --skip-networking flag.`

I make sure that I have the suggested dependencies: 

```
dependencies {
    implementation 'mysql:mysql-connector-java:8.0.28'
    implementation 'org.springframework.boot:spring-boot-starter:2.6.4'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.slack.api:bolt-servlet:1.18.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:2.6.4'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'org.springframework.boot:spring-boot-devtools:2.6.4'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'one.util:streamex:0.8.1'
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation 'com.google.guava:guava:23.0'
    implementation 'com.google.cloud.sql:mysql-socket-factory-connector-j-8:1.4.3'
    testImplementation group: 'org.mockito', name: 'mockito-core', version: '4.3.1'
    testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '4.3.1'
}
```

I can not simply delete `@ServletComponentScan` annotation because the Slack API is depending on that. 
I make sure that my credentials are set up correctly.
## Example code (or command)

com.company.app.config.ConnectionPoolContextListener.createConnectionPool()
```java
    private DataSource createConnectionPool() {
        HikariConfig config = new HikariConfig();


        config.setJdbcUrl(JDBC_URL);

        config.addDataSourceProperty("socketFactory", "com.google.cloud.sql.postgres.SocketFactory");
        config.addDataSourceProperty("cloudSqlInstance", INSTANCE_CONNECTION_NAME);

        config.addDataSourceProperty("ipTypes", "PRIVATE");


        config.setMaximumPoolSize(5);

        config.setMinimumIdle(5);


        config.setIdleTimeout(600000); // 10 minutes

        config.setMaxLifetime(1800000); // 30 minutes
        return pool;
    }
```

com.company.app.MainApplication: 
```java
@SpringBootApplication
@ServletComponentScan
public class MainBotApplication {

    public static void main(String[] args) {
        SpringApplication.run(MainBotApplication.class, args);
    }

}
```
 

## Stacktrace
As I mentioned before, if I don't use `@ServletComponentScan`, my app can make the connection to the MySQL database.

```2022-03-03 14:48:38.628  INFO 33798 --- [  restartedMain] c.e.norberbot.MainBotApplication       : Started NorberBotApplication in 5.827 seconds (JVM running for 6.506)
2022-03-03 14:48:39.214  INFO 33798 --- [onnection adder] c.g.cloud.sql.core.CoreSocketFactory     : Connecting to Cloud SQL instance [myinstance] via SSL socket.
2022-03-03 14:48:40.109  INFO 33798 --- [onnection adder] c.g.cloud.sql.core.CoreSocketFactory     : Connecting to Cloud SQL instance [myinstance] via SSL socket.
2022-03-03 14:48:41.035  INFO 33798 --- [onnection adder] c.g.cloud.sql.core.CoreSocketFactory     : Connecting to Cloud SQL instance [myinstance] via SSL socket.
2022-03-03 14:48:41.875  INFO 33798 --- [onnection adder] c.g.cloud.sql.core.CoreSocketFactory     : Connecting to Cloud SQL instance [myinstance] via SSL socket.
2022-03-03 14:48:42.770  INFO 33798 --- [onnection adder] c.g.cloud.sql.core.CoreSocketFactory     : Connecting to Cloud SQL instance [myinstance] via SSL socket.
2022-03-03 14:48:43.638  INFO 33798 --- [onnection adder] c.g.cloud.sql.core.CoreSocketFactory     : Connecting to Cloud SQL instance [myinstance] via SSL socket.
```

## How to reproduce

  1. If I use `@ServletComponentScan ` the application can not connect to a MySql database. 
  

## Environment

1. OS type and version: Cloud run, mac os.
2. Java SDK version: `openjdk version "15.0.2" 2021-01-19`
2. Socket Factory version: `implementation 'com.google.cloud.sql:mysql-socket-factory-connector-j-8:1.4.3'`

I really appreciate any advice that you could give me. I also made an [issue](https://github.com/slackapi/java-slack-sdk/issues/947) in the slack bolt API

**Comment by kurtisvg** [comment]
Hi @ManuelG28 -- unfortunately I'm not very familiar with SpringBoot, but it seems like this isn't so much a problem with the Cloud SQL Java connector as it is with your SpringBoot configuration. 

My guess is that something with `@ServletComponentScan` is causing your code in the ContextServerListener to not get picked up. When I check out the [docs](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/web/servlet/ServletComponentScan.html) for that annotation is says 
> Typically, one of value, basePackages, or basePackageClasses should be specified to control the packages to be scanned for components. In their absence, scanning will be performed from the package of the class with the annotation.
So maybe it's because your context listener is in a different package? 

However, I'm not even sure that SpringBoot is supposed to use ContextListeners like this. Most of the time, I see SpringBoot users using the gcp-starter and configuring the datasource with a properties file (heres an example [Codelab](https://codelabs.developers.google.com/codelabs/cloud-spring-petclinic-cloudsql#4)). There's also a sample here that use the [Spring Cloud GCP MySQL Starter](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample).

**Comment by ManuelG28** [comment]
Fixed, thank you for your reply @kurtisvg.

https://github.com/slackapi/java-slack-sdk/issues/947#issuecomment-1058620007
