### ISSUE TITLE
Correct Unix Socket logic to correctly identify production run times from development. 

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#77]
A user is having an issue connecting to MySQL on the local App Engine dev server: https://stackoverflow.com/q/50705839/1701388

The root cause is diagnosed here: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3136

In short, Google Cloud Tools for Java set `GAE_RUNTIME` to match the production env when running the local dev server: https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/444. As the code of `SocketFactory` below suggests, it always uses the Unix domain socket if `GAE_RUNTIME` is set. This is especially problematic on Windows.

```java
    // This env will be set by GAE OR set manually if using Cloud SQL Proxy
    String runtime = System.getenv("GAE_RUNTIME");

    if (runtime == null || runtime.isEmpty()) {  // Use standard SSL (direct connection)
      this.socket = SslSocketFactory.getInstance().create(instanceName);
    } else { // Use Unix Socket
      logger.info("Using GAE Unix Sockets");
      UnixSocketAddress socketAddress = new UnixSocketAddress(
          new File(CloudSqlPrefix + instanceName));
      this.socket = UnixSocketChannel.open(socketAddress).socket();
    }
```

Here is what I think is reasonable:
- If `GAE_ENV=localdev`, don't use the Unix domain socket.
or
- Use the Unix socket only when it can find the corresponding socket file under `/cloudsql/`.

Maybe the latter is better, because at least on Linux, users have an option to create a Unix socket locally with the Cloud SQL proxy.

BTW, is there any immediate workaround for the user to make a connection from the local GAE dev server?

**Comment by kurtisvg** [comment]
If the user is this factory, they don't need to be using the proxy at all. The goal of checking for GAE_RUNTIME was to determine if the user was running in GAE (in which case, they use the UNIX socket) or locally (in which case they use the SSL socket). 

The immediate work around would be to use the SslSocketFactory directly when the user is running locally.

Is the GAE_ENV ever set to anything else? Do we have any documentation around it somewhere?

**Comment by chanseokoh** [comment]
> GAE_RUNTIME was to determine if the user was running in GAE

So I think this assumption that you can determine if the user was running in GAE by looking at `GAE_RUNTIME` is wrong. `GAE_RUNTIME` merely tells, e..g, if it is the Java 7 runtime or the Java 8 runtime. Indeed, `GAE_RUNTIME` is being set locally by Google tools as I said (https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/444).

About `GAE_ENV`, I think @ifigotin will know better, who requested us to set them for the local GAE dev server.

But I think it's much better to just check if the socket files exist.

In the mean time, I'll try `SsslScoketFactory`.

**Comment by chanseokoh** [comment]
About `SslSocketFactory`, I just replaced `com.google.cloud.sql.mysql.SslSocketFactory` with `com.google.cloud.sql.core.SslSocketFactory` in the following connection URL, but it gives me an error, probably because `SslSocketFactory` doesn't have a 0-arg constructor.

```java
    String serverURL = "jdbc:mysql://google/mysql?"
        + "cloudSqlInstance=your-gcp-project-id:us-east1:your-mysql-instance-id"
        + "&socketFactory=com.google.cloud.sql.core.SslSocketFactory"
        + "&user=root&password=does-not-matter"
        + "&useSSL=false";

      conn = DriverManager.getConnection(serverURL);
```

```
Caused by: java.lang.InstantiationException: com.google.cloud.sql.core.SslSocketFactory
	at java.lang.Class.newInstance(Class.java:427)
	at com.mysql.jdbc.MysqlIO.createSocketFactory(MysqlIO.java:3328)
	... 46 more
Caused by: java.lang.NoSuchMethodException: com.google.cloud.sql.core.SslSocketFactory.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 47 more
```

**Comment by chanseokoh** [comment]
I see. I have no expertise with Cloud SQL, so I'll leave it up to you for the right fix. Just ensure it uses `SslSocketFactory` on the local dev server where `GAE_RUNTIME` is defined (and also on Windows).

About https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/77#issuecomment-395188521, I guess it doesn't work?

**Comment by kurtisvg** [comment]
> About #77 (comment), I guess it doesn't work?

Sorry, you are correct that it doesn't work. I had forgotten it required the instance name in the url. I will try to escalate this and see if I can get a new version released by the end next week.

**Comment by kurtisvg** [comment]
I tested checking for the existence of a socket, but unfortunately it would cause issues for users that are using the proxy for other applications. Instead I verified a combination of checks with the GAE Java team. 
@chanseokoh PTAL at #86 and make sure it covers your situation correctly.

**Comment by chanseokoh** [comment]
Thanks. According to your explanation and looking at the code, it does look good in that the factory will always use the SSL socket on the local AE dev server.

Just asking: according to https://cloud.google.com/sql/docs/mysql/sql-proxy#multiple-instances, it looked like to me that the user (the Cloud SQL proxy, actually) can create Unix sockets locally and connect to them if they really want to for whatever reasons (only possible on Linux). Seems like this will no longer possible after #86 (although this is not my use case and I don't care much even this is not supported), right? (Or, maybe I misunderstood something.)

**Comment by kurtisvg** [comment]
I'm not sure which part you are concerned about (the multiple instances or using the local unix socket) but both should be possible after #86. 

The Cloud SQL proxy and this library are intended to be parallel connection resources, most (all?) users shouldn't require both. In fact, in it's current state there is no way to force the library to connect using a unix socket - but I did add a check for `"CLOUD_SQL_FORCE_UNIX_SOCKET"` environment variable [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/7cd362c1bb94a6c24aac1221975bf4b3e489abb1/connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java#L55) in case that use case comes up.

**Comment by chanseokoh** [comment]
Never mind. I think I just got something wrong.
