### ISSUE TITLE
How to connect to PostgreSQL with automatic IAM database authentication on JAVA?

### ISSUE THREAD

**Issue by LonwoLonwo** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#823]
Hello, everyone!

I try to connect to PostgreSQL with automatic IAM database authentication on my java application with help of this instruction: https://cloud.google.com/sql/docs/postgres/iam-logins#java-jdbc

I have a PostgreSQL instance on Google Cloud with cloudsql.iam_authentication flag.

The socket factory version is postgres-socket-factory-1.4.4
And PG driver is postgresql-42.2.25

So, I've added all of this properties from the example:

```java
connProps.setProperty("user", DB_USER);
connProps.setProperty("sslmode", "disable");
connProps.setProperty("socketFactory", "com.google.cloud.sql.postgres.SocketFactory");
connProps.setProperty("cloudSqlInstance", CONNECTION_NAME);
connProps.setProperty("enableIamAuth", "true");
```

But I am not sure about password property. Do I need to add setProperty("password", "password") exactly?

I've tried to connect without password property and get:

`org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided.`

Ok, I've added setProperty("password", "password"), but in this case, I've gotten:

```
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:416)
	at org.postgresql.Driver.connect(Driver.java:271)
```

I thought - maybe I need to generate a token from my side and add it as a password property value?

And I tried to:

```java
GoogleCredentials googleCredentials = GoogleCredentials.fromStream(
    Files.newInputStream(
        Path.of(authConfigPath)));
if (googleCredentials != null) {
    GoogleCredentials credentialsScoped = googleCredentials.createScoped(SQLAdminScopes.all());
    if (credentialsScoped != null) {
        AccessToken accessToken = credentialsScoped.refreshAccessToken();
        if (accessToken != null) {
            credentials.setUserPassword(accessToken.getTokenValue());
        }
    }
}
```

but token instead of password is also returned to me: FATAL: password authentication failed for user "postgres".

So, it will be great if you can explain to me - how to use "enableIamAuth" property without the password?
Thank you!

**Comment by shubha-rajan** [comment]
Hi @LonwoLonwo, you shouldn't have to generate your own token if you're using the `enableIamAuth` flag.  You do need to set a password so that the driver won't throw an error, which it looks like you did.  I'm unsure why this is failing. can you try running `gcloud auth print-access-token` and make sure that the token looks valid? Specific things to look for are the length of the token and if the token contains any special characters.

**Comment by shubha-rajan** [comment]
@LonwoLonwo I just noticed that your error message is saying that "password authentication failed for user `postgres`".  When using IAM Authentication, the value of `DB_USER` should be the email address of the IAM user. You'll need to make sure that the email address is added as an IAM user to the database first: https://cloud.google.com/sql/docs/postgres/add-manage-iam-users#creating-a-database-user

**Comment by LonwoLonwo** [comment]
Thanks for the answers.
I've tried to use e-mail instead of login, but no luck.
How can I use `gcloud auth print-access-toke` in my java application? 
I saw my token with the help of credentialsScoped.refreshAccessToken() and it was something like this:

`ya29.c.KqYBCwilziqqtCBnfGaHS7cVtZ9CcFs7w7HthIOZyOE1e9eyaVkgRa6vUaLgC05-t4v6RHNDG8oVlSzIsnx96fmU1AiigdYewNnjGb95K_wkHNC6YL0bOfCti8yG8Y-nmvgFgP_-eFPwB79vL4rpxLLpcW_Xx7cEDH-1Su3Wmm27a3JMFCnFnHOYTZ6MGjHeaj3WjU64OUSyxfkdUbNFOuq086fIQ_6Fzw.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................`

Example from the Internet, but dots and the beginning was the same.

**Comment by kurtisvg** [comment]
@LonwoLonwo It would help if you can provide more detail as to what it is you've tried and if it changed the outcome at all. 

1. Y[ou need to make sure you add the IAM user to the database before you begin](https://cloud.google.com/sql/docs/postgres/add-manage-iam-users#creating-a-database-user)
2. You need to make sure you log in with the user equal to the email you are logging as - e.g. if your IAM user is "lonwo@gmail.com", that's what you use for the db_username
3. The password can be any non-zero value - it get's replaced automatically as long as "enableIAMAuth" is True
4. Finally, if the log in fails make sure to follow the steps in ["Troubleshooting a Login"](https://cloud.google.com/sql/docs/postgres/add-manage-iam-users#creating-a-database-user) to check why the login failed.

**Comment by LonwoLonwo** [comment]
@kurtisvg Thanks. I will look at it.

**Comment by LonwoLonwo** [comment]
Hello. I'm not sure. I think, that the problem in my IAM roles and settings. I can't connect with CLI also.

Hmm. Would you like to test this in our product? We will add this IAM auth setting in the nearest release and will be able to share access to the early version when it appears.

**Comment by kurtisvg** [comment]
I'm going to mark as closed, since you weren't able to connect with the manual approach either. 

If you try again, feel free to try and follow along with the docs and let us know if you run into any issues: https://cloud.google.com/sql/docs/postgres/authentication
