### ISSUE TITLE
Enable GraalVM native image test for all the modules

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#824]
## Feature Description

As of now GraalVM configuration only works for "jdbc/postgres" module. Provide appropriate configurations for other modules ( jdbc/mysql-j-5 jdbc/mysql-j-8  jdbc/sqlserver r2dbc/sqlserver r2dbc/sqlserver r2dbc/mysql).

## Alternatives Considered

N/A

**Comment by suztomo** [comment]
I was thinking to implement it when I created this issue. But I'm afraid that I don't think I can work on this anytime soon. I hope this is not causing any problems in this library.

**Comment by mpeddada1** [comment]
@suztomo I can take this on. Will assign the issue to myself.

**Comment by kurtisvg** [comment]
Thanks @mpeddada1

**Comment by kurtisvg** [comment]
@mpeddada1 any updates on this?

**Comment by enocom** [comment]
Going to close this as stale. Feel free to re-open when we're ready to make progress on this work.
