### ISSUE TITLE
Is it possible to authenticate with Cloud SQL using service account JSON file instead?

### ISSUE THREAD

**Issue by Kool-Koder** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#83]
Hi, I have tried to research alot but still cannot get any clue on how to authenticate to Cloud SQL using a service account. The documentation only talks about application-default credentials, but not service account credentials. Would appreciate the help to point me in the right direction. Thanks!

**Comment by kurtisvg** [comment]
The factory uses the [ApplicationDefaultCredentials](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/) to authenticate as you mentioned. You can set these to a service account (it's the first example on that page).

>   $ gcloud iam service-accounts create my-account
>   $ gcloud iam service-accounts keys create key.json --iam-account=my-account@my-project.iam.gserviceaccount.com
>   $ export GOOGLE_APPLICATION_CREDENTIALS=key.json
>   $ ./my_application.sh

**Comment by Kool-Koder** [comment]
Sorry I don't really understand. I am trying to implement it with Java using Service account JSON file by providing it the path to the JSON file. However, I cannot find where to change it as the factory constantly searches for the application-default credentials. Would appreciate if you can point me in the right direction or provide some sample codes. Thank you very much for your help!

**Comment by kurtisvg** [comment]
You can set the service account that is used by the Application Default Credentials by setting the "GOOGLE_APPLICATION_CREDENTIALS" environment variable as I mentioned above. The factory will then use that service account to connect.

You must use the Application Default Credentials to connect - you can't create a GoogleCredential object and pass it to your SocketFactory in someway at this time.

**Comment by Kool-Koder** [comment]
I see. Thank you for the update! Any idea when there may be support for the ability to create and pass a GoogleCredential object to the SocketFactory? Thanks!

**Comment by kurtisvg** [comment]
No clue, but I believe issue #54 would be the correct issue to follow for updates.

**Comment by Kool-Koder** [comment]
Ok noted. Thanks a lot!
