### ISSUE TITLE
Release 1.0.10 to Maven Central

### ISSUE THREAD

**Issue by anuraaga** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#91]
Thanks for updating the GitHub releases / README with the new version! But I notice even though the README is updated with new docs for 1.0.10, the artifacts haven't been pushed to Central. Just want to make sure this wasn't accidentally missed.

http://central.maven.org/maven2/com/google/cloud/sql/

**Comment by kurtisvg** [comment]
I'm not sure why the artifacts didn't release - I've re-triggered the release lifecycle, so hopefully it'll appear soon.
