### ISSUE TITLE
Library is not compatible with java-9 and above (module-info.java)

### ISSUE THREAD

**Issue by Nikku-jsr** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#952]
From java 9, java introduced modular dependencies logic. As per the logic governs, any backward library(which don't have module-info.java support) where name considered as the package name to use with `requires` in module-info.java. But `com.google.cloud.sql:mysql-socket-factory-connector-j-8:1.6.3` contains `8` in name that make your library incompatible with java 9 and above module. Please find the error message below for the same when we try to use with intelliJ.
```
Caused by: java.lang.IllegalArgumentException: mysql.socket.factory.connector.j.8: Invalid module name: '8' is not a Java identifier
```

Probable fix:
- Add the valid `Automatic-Module-Name` parameter in MANIFEST.MF

Please find the details here: https://www.baeldung.com/java-9-modularity

1. OS type and version: Mac
2. Java SDK version: 16
2. Socket Factory version:

**Comment by kurtisvg** [comment]
Hi @Nikku-jsr -- we do have tests that run Java 11 and Java 17, so it would surprise me to learn that the statement "Library is not compatible with java-9 and above" is true. Can you provide more details on how you are using this library with intellij? 

We have a template [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) that asks some questions about reproducing. If you can specify more information that would be helpful.

**Comment by shubha-rajan** [comment]
Hi @Nikku-jsr, I just opened #953 to add `Automatic-Module-Name` to our manifests. Can you try pulling the branch, building the jar, and adding it to your required modules to test if it works?

**Comment by Nikku-jsr** [comment]
> Hi @Nikku-jsr, I just opened #953 to add `Automatic-Module-Name` to our manifests. Can you try pulling the changes, building the jar, and adding it to your required modules to test if it works?

I feel your solution would work. Just add the version check, I left comment on pr for the same. Otherwise seems good to me.

**Comment by Nikku-jsr** [comment]
I also tested with the maven-jar-plugin version `3.2.2` and its working fine to me. Thanks for the quick response.

**Comment by Nikku-jsr** [comment]
Generated MANIFEST.MF
```
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.2.2
Build-Jdk-Spec: 16
Automatic-Module-Name: com.google.cloud.sql
```
