### ISSUE TITLE
Validate email address format when using IAM authentication

### ISSUE THREAD

**Issue by shubha-rajan** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#954]
**Postgres**: Remove  `.gserviceaccount.com` domain suffix if it exists.
**MySQL**: Remove everything after and including the `@` sign. (`test-user@gmail.com` -> `test-user`)

Should already have `databaseVersion` from the API request to https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/connect/get

**Comment by jackwotherspoon** [comment]
Closing this as a result of investigating IAM AuthN improvements as it seems not feasible across all Connectors.
