### ISSUE TITLE
IDEA 2018.2 DB connection does not work

### ISSUE THREAD

**Issue by driver733** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#96]
I am trying to connect to the Cloud SQL MySQL database using the IntelliJ IDEA IDE 2018.2. I have added the `mysql-socket-factory-1.0.10-jar-with-dependencies.jar` to the the MySQL driver files, however, I get the following error:
```
[08001] Could not create connection to database server. Attempted reconnect 3 times. Giving up.
```
DB connection string :
```
jdbc:mysql://google/dbname?cloudSqlInstance=powerful-gizmo-000000&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&user=foo&password=bar
```

p.s. I have been able to connect to the db using Google Apps script

**Comment by kurtisvg** [comment]
Do you have Default Application Credentials set correctly? Did you try the 'Test Connection' link on the driver configuration page?

**Comment by kurtisvg** [comment]
Closing - more than 30 days without response.
