### ISSUE TITLE
Logstash implementation

### ISSUE THREAD

**Issue by llermaly** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#965]
## Question

I need to query CloudSQL from Logstash but can find any example out there.

## Additional Context

I ran the build command for postgres jdbc driver 

`mvn -P jar-with-dependencies clean package -DskipTests`

And provided it as Logstash JDBC driver (tried with dependencies jar too):

```
input {
    jdbc {
        jdbc_driver_library => "/Users/gustavollermalylarrain/Documents/proyectos/labs/cloud-sql-jdbc-socket-factory/jdbc/postgres/target/postgres-socket-factory-1.6.4-SNAPSHOT.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        jdbc_connection_string => "jdbc:postgresql:///people?cloudSqlInstance=xxx-xxx-148903:us-central1:llermaly&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=postgres"
        statement => "SELECT * FROM people;"
        jdbc_user => "postgres"
        jdbc_password => "postgres"
    }
}

output {
    stdout {
        codec => rubydebug {
        }
    }
}
```

I'm having this error: 

> Error: java.lang.ClassNotFoundException: org.postgresql.Driver. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?

I'm missing something?

Thank you

**Comment by llermaly** [comment]
Solved it: 

https://stackoverflow.com/questions/73547585/cloudsql-jdbc-logstash-implementation/73550954#73550954

Thank you

**Comment by enocom** [comment]
Thanks for the update @llermaly.

**Comment by llermaly** [comment]
my pleasure
