### ISSUE TITLE
Support MariaDB R2DBC driver

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#990]
Right now, only the MySQL driver is supported in socket factory. Unfortunately, the driver is no longer maintained, and Spring recommendation is [to use the MariaDB driver](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#r2dbc-driver-changes). They should be protocol-compatible.

This will require adding a new `ConnectionFactoryProvider` similar to the existing `GcpConnectionFactoryProviderMysql`.

**Comment by elefeint** [comment]
@JoeWang1127 Could you take a look at implementing the MariaDB R2DBC support in this repo? @mpeddada1 implemented the original MySQL/CloudSQL autoconfiguration in Spring Cloud GCP that's based on the R2DBC connection factories in this repo.

**Comment by JoeWang1127** [comment]
Sure, will do

**Comment by elefeint** [comment]
This is blocked on adding the SSL tunneling capability into the MariaDB driver.

**Comment by shubha-rajan** [comment]
Following up on this since the SSL Tunnel mode patch has landed. Do we plan to finish this implementation soon?
